# -------------------------- SUB QUERIES -----------------------------

# NOTE : QUERY INSIDE ANOTHER QUERY CALLED SUB-QUERY OR NESTED QUERY.
# 		 SUB-QUERY IN WHERE CLAUSE
# 		 1. SINGLE ROW SUB-QUERY - WORK WITH OPERATORS SUCH AS >,<,>=,<=,=,!=
# 		 2. MULTI ROW SUB-QUERY  - WORK WITH OPERATORS SUCH AS IN,ALL,ANY

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    order_amount DECIMAL(10,2),
    order_date DATE
);

INSERT INTO orders (order_id, customer_id, order_amount, order_date) VALUES
(101, 1, 5000.00, '2025-01-01'),
(102, 2, 10000.00, '2025-01-02'),
(103, 3, 3000.00, '2025-01-03'),
(104, 4, 1500.00, '2025-01-04'),
(105, 1, 7000.00, '2025-01-05'),
(106, 5, 8000.00, '2025-01-06');

SELECT * FROM CUSTOMERS;

1	Ravi Kumar	    ravi.kumar@example.com	    Chennai	    43210
2	Priya Sharma	priya.sharma@example.com	Bangalore	43211
3	Arjun Mehta	    arjun.mehta@example.com	    Hyderabad	43212
4	Meena Gupta	    meena.gupta@example.com	    Mumbai	
5	Karthik Raj	    karthik.raj@example.com	    Chennai	    43213

SELECT * FROM ORDERS;

101	1	5000.00	    2025-01-01
102	2	10000.00	2025-01-02
103	3	3000.00	    2025-01-03
104	4	1500.00	    2025-01-04
105	1	7000.00	    2025-01-05

# WAY - 1
SELECT 
	CUSTOMER_NAME,
    (SELECT MAX(ORDER_AMOUNT) FROM ORDERS) AS MAX_ORDER_AMOUNT
FROM CUSTOMERS;

Ravi Kumar	    10000.00
Priya Sharma	10000.00
Arjun Mehta	    10000.00
Meena Gupta	    10000.00
Karthik Raj	    10000.00

# WAY - 2
SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE ID IN (SELECT DISTINCT CUSTOMER_ID FROM ORDERS WHERE ORDER_AMOUNT >= 5000);

Ravi Kumar
Priya Sharma
Karthik Raj

# WAY - 3
SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE EXISTS (SELECT * FROM CUSTOMERS WHERE CITY = "CHENNAI");

Ravi Kumar
Priya Sharma
Arjun Mehta
Meena Gupta
Karthik Raj

SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE EXISTS (SELECT * FROM CUSTOMERS WHERE CITY = "NELLAI");

# NOTHING WILL DISPLAY

# WAY - 4 - WITHOUT JOIN
SELECT CUSTOMER_NAME,(SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) AS TOTAL_AMOUNT FROM CUSTOMERS;

Ravi Kumar	    12000.00
Priya Sharma	10000.00
Arjun Mehta	    3000.00
Meena Gupta	    1500.00
Karthik Raj	    8000.00

# WAY - 5 - FROM
SELECT 
	LENGTH_OF_CUSTOMER_NAME,
    CUSTOMER_NAME_IN_UPPERCASE,
    EMAIL_IN_LOWERCASE,
    NAME_CITY_CONCAT,
    SUBSTRING_CUSTOMER_NAME_1_6,
    TRIMMING,
    LEFT_TRIMMING,
    RIGHT_TRIMMING,
    LEFT_PADDING,
    RIGHT_PADDING,
    CUSTOMER_NAME_REPLACED,
    POSITION_OF_A,
    FIRST_FIVE_CH_IN_CNAME,
    LAST_THREE_CH_IN_CNAME,
    REVERSED_CITY,
    FORMATTED_PHONE,
    INSIDE_UPPER_REPLACED
FROM (
	SELECT CUSTOMER_NAME,
	LENGTH(CUSTOMER_NAME) AS LENGTH_OF_CUSTOMER_NAME,
	UPPER(CUSTOMER_NAME) AS CUSTOMER_NAME_IN_UPPERCASE,
	LOWER(EMAIL) AS EMAIL_IN_LOWERCASE,
	CONCAT(CUSTOMER_NAME,' - ',CITY) AS NAME_CITY_CONCAT,
	SUBSTRING(CUSTOMER_NAME,1,6) AS SUBSTRING_CUSTOMER_NAME_1_6,
	TRIM('     TRIMMING      ') AS TRIMMING,
	LTRIM('     TRIMMING      ') AS LEFT_TRIMMING,
	RTRIM('     TRIMMING      ') AS RIGHT_TRIMMING,
	LPAD(CITY,10,'*') AS LEFT_PADDING,
	RPAD(CITY,10,'#') AS RIGHT_PADDING,
	REPLACE(CUSTOMER_NAME,' ','_') AS CUSTOMER_NAME_REPLACED,
	INSTR(CUSTOMER_NAME,'a') AS POSITION_OF_A,
	LEFT(CUSTOMER_NAME,5) AS FIRST_FIVE_CH_IN_CNAME,
	RIGHT(CUSTOMER_NAME,3) AS LAST_THREE_CH_IN_CNAME,
	REVERSE(CITY) AS REVERSED_CITY,
	FORMAT(PHONE_NUMBER,3) AS FORMATTED_PHONE,
	UPPER(REPLACE(CUSTOMER_NAME,' ','_')) AS INSIDE_UPPER_REPLACED
	FROM CUSTOMERS
    ) AS SUB_QUERY;

( NOTE : ABOVE ADVANTAGE IS WE CAN DISPLAY ONLY WHAT WE NEED THAT THINGS ONLY WE CAN ADD TO QUERY BUT ALL THE INNER QUERIES ARE EXECUTED BUT WE CAN RESTRICT WHAT DISPLAY IN OUTER SUBQUERY)

# WAY - 6 - WHEN

SELECT CUSTOMER_NAME,
CASE
	WHEN (SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) > (SELECT AVG(ORDER_AMOUNT) FROM ORDERS) THEN 'ABOVE_AVERAGE'
    ELSE 'BELOW AVERAGE'
END AS AMOUNT_CATEGORY
FROM CUSTOMERS;

Ravi Kumar	    ABOVE_AVERAGE
Priya Sharma	ABOVE_AVERAGE
Arjun Mehta	    BELOW AVERAGE
Meena Gupta	    BELOW AVERAGE
Karthik Raj	    ABOVE_AVERAGE

SELECT CUSTOMER_NAME,LOWER(AMOUNT_CATEGORY) FROM (
SELECT CUSTOMER_NAME,
CASE
	WHEN (SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) > (SELECT AVG(ORDER_AMOUNT) FROM ORDERS) THEN 'ABOVE_AVERAGE'
    ELSE 'BELOW AVERAGE'
END AS AMOUNT_CATEGORY
FROM CUSTOMERS) AS AMOUNT_CATEGORY;

Ravi Kumar	    above_average
Priya Sharma	above_average
Arjun Mehta	    below average
Meena Gupta	    below average
Karthik Raj	    above_average