# ----------------------------- JOIN TABLES --------------------------------------

CREATE TABLE RESTAURANTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    LOCATION VARCHAR(50)
);

INSERT INTO RESTAURANTS (ID, NAME, LOCATION) VALUES
(1, 'ABC Bistro', 'New York'),
(2, 'The Foodie', 'Los Angeles'),
(3, 'Tasty Treat', 'Chicago');

CREATE TABLE RESTAURANTS_ORDERS (
    ORDER_ID INT PRIMARY KEY,
    RESTAURANT_ID INT,
    ORDER_DATE DATE
);

INSERT INTO RESTAURANTS_ORDERS (ORDER_ID, RESTAURANT_ID, ORDER_DATE) VALUES
(1, 1, '2023-01-01'),
(2, 1, '2023-01-02'),
(3, 2, '2023-01-05'),
(4, 4, '2023-01-07');

# -------------------------------------- JOIN -> INNER JOIN --------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

ABC Bistro	2023-01-01
ABC Bistro	2023-01-02
The Foodie	2023-01-05

# ------------------------------------- LEFT JOIN -------------------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
LEFT JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

ABC Bistro	2023-01-02
ABC Bistro	2023-01-01
The Foodie	2023-01-05
Tasty Treat	

# ------------------------------------- RIGHT JOIN -------------------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
RIGHT JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

ABC Bistro	2023-01-01
ABC Bistro	2023-01-02
The Foodie	2023-01-05
	        2023-01-07

# ------------------------------------- SELF JOIN ------------------------------------------------

CREATE TABLE SELF_JOIN_TABLE(
	ID INT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
    MANAGER_ID INT NULL
);

INSERT INTO SELF_JOIN_TABLE
VALUES(1,'VIJAY',3),
(2,'SWATHI',3),
(3,'DHEEKSHA',NULL),
(4,'DIYA',3);

SELECT 
	F.NAME AS EMPLOYEE_NAME,
    S.NAME AS MANAGER_NAME
FROM SELF_JOIN_TABLE F
LEFT JOIN SELF_JOIN_TABLE S
ON F.MANAGER_ID = S.ID;

VIJAY	    DHEEKSHA
SWATHI	    DHEEKSHA
DHEEKSHA	
DIYA	    DHEEKSHA

# NOTE : IN MY SQL FULL OUTER JOIN KEYWORD WONT WORK SO WE MUST USE SET OPERATORS -> UNION, UNION ALL, INTERSECT, EXCEPT
#		 IN SET OPERATORS COLUMN COUNT SHOULD BE MATCHED.
# 		 DATA AND COLUMN NAME NOT NECESSARY,BUT THE DATATYPE SHOULD BE SAME.
#        GO TO 15_UNION.sql QUESTION.

# ---------------------------------- CROSS JOIN ---------------------------------

# NOTE : CARTISIEAN PRODUCT - CROSS JOIN
#        IF WE HAVE 3 TABLES AND EACH HAVE 3 ROWS THEN RESULTANT ROWS SHOULD BE 3 * 3 

CREATE TABLE TOPPINGS(
	TOPPINGS VARCHAR(25)
);

INSERT INTO TOPPINGS VALUES('MUSHROOM'),('PANEER'),('OLIVES');

CREATE TABLE SIZES(
	SIZE VARCHAR(10)
);

INSERT INTO SIZES VALUES('SMALL'),('MEDIUM'),('LARGE');

CREATE TABLE CRUST(
	TYPE CHAR(10)
);

INSERT INTO CRUST VALUES('THIN'),('THICK');

SELECT T.TOPPINGS,S.SIZE,C.TYPE
FROM TOPPINGS T CROSS JOIN SIZES S CROSS JOIN CRUST C;

OLIVES	    SMALL	THIN
OLIVES	    SMALL	THICK
PANEER	    SMALL	THIN
PANEER	    SMALL	THICK
MUSHROOM	SMALL	THIN
MUSHROOM	SMALL	THICK
OLIVES	    MEDIUM	THIN
OLIVES	    MEDIUM	THICK
PANEER	    MEDIUM	THIN
PANEER	    MEDIUM	THICK
MUSHROOM	MEDIUM	THIN
MUSHROOM	MEDIUM	THICK
OLIVES	    LARGE	THIN
OLIVES	    LARGE	THICK
PANEER	    LARGE	THIN
PANEER	    LARGE	THICK
MUSHROOM	LARGE	THIN
MUSHROOM	LARGE	THICK