# --------------------- WINDOW FUNCTIONS -----------------------------------------------

NOTE :
    
    1. A WINDOW FUNCTIONS IN SQL PERFORMS A CALCULATION ACROSS A SET OF ROWS RELATED TO THE CURRENT ROW.
    2. WITHOUT CHANGING THE NUMBER OF ROWS IN THE  RESULT SET.
    3. THE TERM WINDOW REFERS TO A SET OF ROWS THAT ARE SOME HOW RELATED TO THE CURRENT ROW.

THREE TYPES :

    1. AGGREATE : ( AVG(), MAX(), MIN(), SUM(), COUNT() )
    2. RANKING  : ( ROW_NUMBER(), RANK(), DENSE_RANK(), PERCENT_RANK(), NTILE() )
    3. VALUE    : ( LAG(), LEAD(), FIRST_VALUE(), LAST_VALUE(), NTH_VALUE() )

CREATE TABLE SALES(
	TRANSACTION_ID INT,
    STORE VARCHAR(20),
    SALES_AMOUNT DECIMAL(10,2)
);

INSERT INTO SALES
VALUES(1,'A',100.00),(2,'A',200.00),(3,'A',150.00),(4,'B',250.00),(5,'B',300.00);

SELECT * FROM SALES;

1	A	100.00
2	A	200.00
3	A	150.00
4	B	250.00
5	B	300.00

# STORE WISE TRANSACTION

POINTS TO REMEMBER :

    1. IN GROUP BY WE ONLY GIVE ONE FIELD WHICH IS COMES UNDER GROUP BY.
    2. THE RESULTANT ROWS ARE SHRINK.
    3. WINDOW FUNCTIONS OVERCOME THESE DISADVANTAGES.

SELECT STORE,SUM(SALES_AMOUNT) AS AMOUNT FROM SALES
GROUP BY STORE;

A	450.00
B	550.00

POINTS TO REMEMBER :

    1. WE CAN GIVE MORE FIELDS IN DISPLAYING SECTION.
    2. OVER() -> DID AGGREATE ALL THE VALUES AND INSERTED INTO EVERY ROW.

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER()
FROM SALES;

1	A	100.00	1000.00
2	A	200.00	1000.00
3	A	150.00	1000.00
4	B	250.00	1000.00
5	B	300.00	1000.00

POINTS TO REMEMBER :

    1. PARTITION BY -> USED TO PERFORM OPERATION BASED ON PARTITION BY.
    2. IN THIS SECTION CALCULATE THE SUM AMOUNT BASED ON STORE WHICH MEANS A HAS TOTAL AND B HAS SOME TOTAL LIKE WISE.
    3. ONE DIFF IS IN GROUP BY WE CANT USE MORE FIELDS DISPLAY BUT HERE WE CAN USE IT BY WINDOW FUNCTION.

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER(PARTITION BY STORE) AS TOTAL
FROM SALES;

1	A	100.00	450.00
2	A	200.00	450.00
3	A	150.00	450.00
4	B	250.00	550.00
5	B	300.00	550.00

POINTS TO REMEMBER :

    1. HERE PARTITION BY STORE -> CALCULATE THE TOTAL AMOUNT BUT ORDER BY TRANSACTION_ID GIVES LIKE FIRST FIND TOTAL AND PUT IT AND NEXT FIND TOTAL AND ADD IT AND PUT IT LIKE WISE.
    2. BUT STORE WISE.

    ( EXAMPLE : MILK MAN POUR 1/2 LTR MILK WHICH IS 25 FOR FIRST DAY AND NEXT DAY CAME AND POUR 1 LTR WHICH COST IS 50 SO MILK MAN TOLD PENDING AMOUTN IS 75 ALONG TODAY ITSELF.
                NEXT DAY CAME AND POUR 1 LTR WHICH COST IS 50 SO TOTAL IS 125 FROM DAY 1 TO TILL.
                LIKE WISE ORDER BY PERFORMS IN WINDOW FUNCTION
    )
SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY TRANSACTION_ID) AS TOTAL
FROM SALES;

1	A	100.00	100.00
2	A	200.00	300.00
3	A	150.00	450.00
4	B	250.00	250.00
5	B	300.00	550.00

# ---------------------------------- RANKING WINDOW FUNCTIONS ---------------------------------------

# 1. ROW_NUMBER()

POINTS TO REMEMBER :

    1. AS IT IS GIVE THE ROW_NUMBER NO CHANGING.
    2. IT JUST INSERT ROW_NUMBER FOR EACH ROW BECAUSE WE NOT MENTIONED ANY.

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER() AS ROW_NUM
FROM SALES;

1	A	100.00	1
2	A	200.00	2
3	A	150.00	3
4	B	250.00	4
5	B	300.00	5

POINTS TO REMEMBER :

    1. FIRST SORTING THE ROWS BASED ON SALES_AMOUNT BECAUSE WE USED ORDER_BY INSIDE OVER.
    2. THEN GAVE THE ROW_NUMBER FOR EACH ROW.

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER(ORDER BY SALES_AMOUNT DESC) AS ROW_NUM
FROM SALES;

5	B	300.00	1
4	B	250.00	2
2	A	200.00	3
3	A	150.00	4
1	A	100.00	5

POINTS TO REMEMBER :

    1. IN THIS GROUP BY STORE THEN SORTING BASED ON SALES_AMOUNT.
    2. GIVE NUMBER ORDER TO STORE WISE.
    3. A STORE SORTING BY SALES_AMOUNT IN DESCENDING ORDER AND GIVE ROW_NUMBER FOR EACH ROW IN STORE A ALONE.
    4. B STORE SORTING BY SALES_AMOUNT IN DESCENDING ORDER AND GIVE ROW_NUMBER FOR EACH ROW IN STORE B ALONE.

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT DESC) AS ROW_NUM
FROM SALES;

2	A	200.00	1
3	A	150.00	2
1	A	100.00	3
5	B	300.00	1
4	B	250.00	2

# --------------------- ROW_NUMBER REAL SCENERIO --------------------------

CREATE TABLE EMP_WINDOW(
	EMP_ID INT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(40),
    HIRE_DATE DATE
);

INSERT INTO EMP_WINDOW
VALUES
(1, 'ALICE', 'HR', '2020-05-01'),
(1, 'ALICE', 'HR', '2022-06-15'),
(2, 'BOB', 'IT', '2021-07-10'),
(3, 'CHARLIE', 'FINANCE', '2020-09-30'),
(3, 'CHARLIE', 'FINANCE', '2022-05-22');

SELECT * FROM EMP_WINDOW;

POINTS TO REMEMBER :

    1. HERE GIVE A ROW_NUMBER TO EVERY EMP_ID WHICH IS ORDER BY HIRE_DATE IN ASCENDING ORDER.

SELECT 
	EMP_ID,NAME,DEPARTMENT,HIRE_DATE,
    ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY HIRE_DATE ASC) AS ROW_NUM
FROM EMP_WINDOW;

1	ALICE	HR	    2020-05-01	1
1	ALICE	HR	    2022-06-15	2
2	BOB	    IT	    2021-07-10	1
3	CHARLIE	FINANCE	2020-09-30	1
3	CHARLIE	FINANCE	2022-05-22	2

POINTS TO REMEMBER :

    1. HERE GIVE A ROW_NUMBER TO EVERY EMP_ID WHICH IS ORDER BY HIRE_DATE IN ASCENDING ORDER.
    2. AND USE CTE FOR AVOIDING DUPLICATE.
    3. NOW SENDS REPORT TO THE TEAM WITHOUT REPEATATING.

WITH EMP_WINDOW_CTE AS 
(SELECT 
	EMP_ID,NAME,DEPARTMENT,HIRE_DATE,
    ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY HIRE_DATE ASC) AS ROW_NUM
FROM EMP_WINDOW)

SELECT EMP_ID,NAME,DEPARTMENT,HIRE_DATE FROM EMP_WINDOW_CTE WHERE ROW_NUM = 1;

1	ALICE	HR	    2020-05-01
2	BOB	    IT	    2021-07-10
3	CHARLIE	FINANCE	2020-09-30

# 2. RANK(), DENSE_RANK()

CREATE TABLE STUDENT_WINDOW(
	 STUDENT_ID INT,
     STUDENT_NAME VARCHAR(20),
     SCORE INT
);

INSERT INTO STUDENT_WINDOW
VALUES
(1, 'ALICE', 95),
(2, 'BOB', 90),
(3, 'CHARLIE', 95),
(4, 'DAVID', 85),
(5, 'EVA', 90);

POINTS TO REMEMBER :

    1. RANK() -> IF TWO ROWS ARE SAME THE PUT 1 FOR EACH AND NEXT ROW PUT 3 BECAUSE IT WORKS AS COUNT WISE.

SELECT
	STUDENT_ID, STUDENT_NAME, SCORE,
    RANK() OVER(ORDER BY SCORE DESC) AS RANK_OF_STUDENT
FROM STUDENT_WINDOW;

1	ALICE	95	1
3	CHARLIE	95	1
2	BOB	    90	3
5	EVA	    90	3
4	DAVID	85	5

POINTS TO REMEMBER :

    1. DENSE_RANK() -> IT WORKS AS IF BOTH ARE IN RANK 1 THEN PUT 1 FOR BOTH AND NEXT ROW NUMBER IS 2 AS WELL AS.
    2. THIS IS THE ONLY DIFF BETWEEN RANK() AND DENSE_RANK().

SELECT
	STUDENT_ID, STUDENT_NAME, SCORE,
    DENSE_RANK() OVER(ORDER BY SCORE DESC) AS RANK_OF_STUDENT
FROM STUDENT_WINDOW;

1	ALICE	95	1
3	CHARLIE	95	1
2	BOB	    90	2
5	EVA	    90	2
4	DAVID	85	3