# ------------------------- UNION AND UNION ALL -----------------------------------

CREATE TABLE EMPLOYEES_UNION (
	EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	POSITION VARCHAR(50),
	SALARY DECIMAL(10,2)
);

CREATE TABLE CONTRACTORS_UNION (
	CONTRACTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	POSITION VARCHAR(50),
	HOURLY_RATE DECIMAL (10,2)
);

INSERT INTO EMPLOYEES_UNION(FIRST_NAME,LAST_NAME,POSITION,SALARY)
VALUES
('ALICE', 'SMITH', 'DEVELOPER', 70000.00), ('BOB', 'JOHNSON', 'DEVELOPER', 75000.00),
('CHARLIE', 'LEE', 'MANAGER', 90000.00);

INSERT INTO CONTRACTORS_UNION (FIRST_NAME,LAST_NAME,POSITION,HOURLY_RATE)
VALUES
('DAVE', 'WILLIAMS', 'DEVELOPER', 40.00),
('EVE', 'BROWN', 'TESTER', 35.00),
('BOB', 'JOHNSON', 'DEVELOPER', 45.00);

POINTS TO REMEMBER:

    1. IT COMBINES BOTH THE TABLES.
    2. NOTE -> TWO TABLES MUST HAVE SAME NO OF COLUMNS THEN ONLY IT RUNS OTHERWISE IT THROWS ERROR.
    3. AND OUTPUT FIELDS DISPLAYS FIRST TABLE MENTIONED NAME.

SELECT * FROM EMPLOYEES_UNION
UNION ALL
SELECT * FROM CONTRACTORS_UNION;

EMPLOYEE_ID     FIRST_NAME  LAST_NAME   POSITION    SALARY
1	            ALICE	    SMITH	    DEVELOPER	70000.00
2	            BOB	        JOHNSON	    DEVELOPER	75000.00
3	            CHARLIE	    LEE	        MANAGER	    90000.00
1	            DAVE	    WILLIAMS	DEVELOPER	40.00
2	            EVE	        BROWN	    TESTER	    35.00
3	            BOB	        JOHNSON	    DEVELOPER	45.00

SELECT * FROM EMPLOYEES_UNION
UNION
SELECT * FROM CONTRACTORS_UNION;

EMPLOYEE_ID     FIRST_NAME  LAST_NAME   POSITION    SALARY
1	            ALICE	    SMITH	    DEVELOPER	70000.00
2	            BOB	        JOHNSON	    DEVELOPER	75000.00
3	            CHARLIE	    LEE	        MANAGER	    90000.00
1	            DAVE	    WILLIAMS	DEVELOPER	40.00
2	            EVE	        BROWN	    TESTER	    35.00
3	            BOB	        JOHNSON	    DEVELOPER	45.00

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
UNION ALL
SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;

FIRST_NAME  LAST_NAME
ALICE       SMITH
BOB         JOHNSON
CHARLIE     LEE
DAVE        WILLIAMS
EVE         BROWN
BOB         JOHNSON

POINTS TO REMEMBER:

    1. IT COMBINES BOTH THE TABLES.
    2. NOTE -> SELECT FIELDS SHOULD BE SAME NO OF COLUMNS THEN ONLY IT RUNS OTHERWISE IT THROWS ERROR.
    3. ONLY DIFF BETWEEN UNION AND UNION ALL IS UNION ELIMINATE THE DUPLICATION.
    4. HERE BOB JOHNSON CAME BOTH THE TABLES BUT IF WE USE UNION ALL IT CREATES DUPLICATES WHILE DISPLAYING FIRST_NAME AND LAST_NAME.
    5. BUT IF WE ARE USING UNION IT ELIMINATE THE DUPLICATION THIS IS THE MAJOR DIFF.

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
UNION
SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;

FIRST_NAME  LAST_NAME
ALICE       SMITH
BOB         JOHNSON
CHARLIE     LEE
DAVE        WILLIAMS
EVE         BROWN