# ------------------------------------------ REGEX ---------------------------------------------------

CREATE TABLE REGEX_SAMPLES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    SAMPLE_TEXT VARCHAR(100)
);

INSERT INTO REGEX_SAMPLES(SAMPLE_TEXT) VALUES
('APPLE'),('BANANA'),('CHERRY'),('DATE'),('ELDERBERRY'),('FIG'),('GRAPE'),('HONEYDEW'),('RUNNING'),('123ABC');

SELECT * FROM REGEX_SAMPLES;

# --------------------------------- CHEAT SHEET ---------------------------------

^      - START OF STRING ANCHOR          - ASSERTS THAT THE FOLLOWING PATTERN MUST OCCUR AT THE BEGINNING OF THE STRING.    - ^Hello MATCHES "HELLO WORLD"
$      - END   OF STRING ANCHOR          - ASSERTS THAT THE PRECEDING PATTERN MUST OCCUR AT THE END OF THE STRING.          - WORRD$ MATCHES "HELLO WORLD"
.      - ANY CHARACTER                   - MATCHES ANY SINGLE CHARACTER EXCEPT A NEWLINE.                                   - A.C MATCHES "ABC","A-B","A.C"
*      - ZERO OR MORE                    - MATCHES ZERO OR MORE OCCURENCES OF THE PRECEDING ELEMENT.                        - AB*C MATCHES "AC","ABC","ABBC",ETC 
+      - ONE OR MORE                     - MATCHES ONE OR MORE OCCURENCES OF THE PRECEDING ELEMENT.                         - AB+C MATCHES "ABC","ABBC" BUT NOT "AC"  
?      - ZERO OR ONE                     - MATCHES ZERO OR ONE OCCURENCES OF THE PRECEDING ELEMENT.                         - COLOU?R MATCHES BOTH "COLOR" AND "COLOUR"
{N}    - EXACT COUNT                     - MATHCES EXACTLY N OCCURENCES OF THE PRECEDING ELEMENT.                           - A{3} MATCHES "AAA"
{N,}   - ATLEAST N OR MORE OCCURENCES    - MATCHES N OR MORE OCCURENCES OF THE PRECEDING ELEMENT.                           - A{2,} MATCHES "AA","AAAA","AAAA",ETC
{N,M}  - RANGE OF OCCURENCES             - MATCHES BETWEEN N AND M OCCURENCES OF THE PRECEDING ELEMENT.                     - A{2,4} MATCHES "AA","AAA","AAAA"
[ABC]  - CHARACTER CLASS                 - MATCHES ANY ONE OF THE CHARACTERS ENCLOSED IN THE BRACKETS.                      - [ABC] MATCHES "A","B" OR "C"
[^ABC] - NEGATED CHARACTER CLASS         - MATCHES ANY CHARACTER NOT LISTED BETWEEN THE BRACKETS.                           - [^ABC] MATCHES ANY CHARACTER EXCEPT "A","B","C"
(ABC)  - GROUPING AND CAPTURING          - GROUPS THE CHARACTERS "ABC" TOGETHER, WHICH CAN THEN BE REFERENCED LATER.        - (ABC)+ MATCHES "ABC","ABCABC",ETC
|      - ALTERNATION(OR)                 - MATCHES THE EXPRESSION BEFORE OR AFTER THE | SYMBOL.                             - CAT|DOG MATCHES "CAT" OR "DOG"           
\d     - DIGIT CHARACTER                 - MATCHES ANY SINGLE DIGIT(EQUIVALENT TO [0-9])                                    - \d MATCHES "0","1",....
\D     - NON DIGIT CHARACTER             - MATCHES ANY CHARACTER THAT IS NOT A DIGIT.                                       - \D MATCHES LETTER OR SYMBOL
\W     - NON WORD CHARACTER              - MATCHES ANY CHARACTER THAT IS NOT A WORD CHARACTER.                              - \W MATCHES PUNCTUATION AND SPACES,ETC
\w     - WORD CHARACTER                  - MATCHES ANY ALPHANUMERIC CHARACTER OR UNDERSCORE(EQUIVALENT TO [A-Za-z0-9]_)     - \w MATCHES LETTERS,DIGITS AND UNDERSCORE.
\s     - WHITESPACE CHARACTER            - MATCHES SPACES,TABS,NEWLINES AND OTHER WHITESPACE.                               - \s MATCHES SINGLE SPACES OR TAB.
\S     - NON-WHITESPACE CHARACTER        - MATCHES ANY CHARACTER THAT IS NOT WHITESPACE.                                    - \S MATCHES LETTERS,DIGITS AND PUNCTUATION AND ETC.
\b     - WORD BOUNDARY                   - ASSERTS A POSITION BETWEEN A WORD CHARACTER AND A NON WORD CHARACTER.            - \bWORD\b MATCHES "WORD" AS A WHOLE WORD (NOT PART OF "SWORD" OR "WORDS")
\B     - NON WORD BOUNDARY               - ASSERTS A POSITION THAT IS NOT A WORD BOUNDARY.                                  - \Bend MIGHT MATCH "bend" WITHIN A LONGER WORD LIKE "amendment"

CREATE TABLE REGEX_SAMPLES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    SAMPLE_TEXT VARCHAR(100)
);

INSERT INTO REGEX_SAMPLES(SAMPLE_TEXT) VALUES
('APPLE'),('BANANA'),('CHERRY'),('DATE'),('ELDERBERRY'),('FIG'),('GRAPE'),('HONEYDEW'),('RUNNING'),('123ABC');

SELECT * FROM REGEX_SAMPLES;

SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^A';                  # MATCHES STARTING WITH A CHARACTER
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'ING$';                # MATCHES ENDING WITH ING CHARACTER
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]';              # MATCHES ONLY NUMERIC VALUES 0 TO 9
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '(.)\\1';              # MATCHES ONLY TWO CONTINUES LETTER WORDS JUST LIKE APPLE,FERRY BECAUSE IN THIS P AND R CONTINUES SO.
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Za-z]+$';         # MATCHES A SENTENCE WHICH CONTAINS ONLY LETTERS
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^.{5}$';              # MATCHES ANY FIVE CHARACTER WORDS
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^(APPLE|BANANA)$';    # MATCHES ONLY APPLE AND BANANA
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]{3}[A-Z]+$';    # MATCHES ONLY STARTING WITH 3 NUMERIC AND AFTER THAT LETTERS WORDS

CREATE TABLE REGEX_DEMO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	full_name VARCHAR(50),
	phone VARCHAR(25),
	email VARCHAR(100),
	date_col VARCHAR(10),
	status VARCHAR(20),
	sku VARCHAR(20),
	username VARCHAR(30),
	notes VARCHAR(100)
);

INSERT INTO REGEX_DEMO (full_name, phone, email, date_col, status, sku, username, notes)
VALUES
('John Smith','123-456-7890','john@example.com','2025-02-07','pending','ABCD','johnsmith','Ships to CA'),
('Alice Johnson','(987) 654-3210','alice@@example.net','2025-02-07','inactive','SKU-123','alice','NY location'),
('Bob Williams','+1-555-123-4567','bob@sample.org','20250207','complete','1SKU','bob123','Shipping to CA'),
('Mary 1 White','(123) 123-4567','mary123@example.com','2025-13-31','PENDING','abc-999','mary_white','Something about CA or'),
('Mark-Spencer','1234567890','mark@example.com','2024-11-02','active','SKU-9999','mark','Random note'),
('Jane O''Connor','1987-654-3210','jane.o.connor@example.org','2024-12-31','inactive','ABCDE','JaneO','Contains CA or NY'),
('Invalid Mail','000-000-0000','invalid@@example..com','2023-01-15','inactive','XYZeee','invalid','Double and dots'),
('NoSpacesHere','+12-345-678-9012','nospaces@example.co','2025-02-07','pending','SKU999','NoSpaces','Ends with.co domain');

SELECT * FROM REGEX_DEMO;

SELECT ID,FULL_NAME,DATE_COL FROM REGEX_DEMO WHERE DATE_COL REGEXP '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$'; # DISPLAYING ONLY VALID DATE FORMAT ('YYYY-MM-DD')
SELECT ID,FULL_NAME FROM REGEX_DEMO WHERE FULL_NAME REGEXP '^[A-Za-z ]+$'; # MATCHES NAMES CONTAINING ONLY LETTERS AND SPACES