# ------------------------------------------- TCL - COMMIT AND ROLLBACK AND SAVEPOINT ----------------------------------------------

# NOTE : TCL - TRANSACTION CONTROL LANGUAGE -> MANAGE TRANSACTION WITHING THE DATABASE.

# POINTS TO REMEMBER : 
# 1. COMMIT    - TO SAVE TRANSACTION PERMANENTLY
# 2. ROLLBACK  - TO UNDO TRANSACTION
# 3. SAVEPOINT - TO SET A POINT WITHTIN A TRANSACTION TO WHICH YOU CAN ROLL BACK

# SCENERIO - 1

CREATE ONE TABLE
INSERT TWO ROWS
INSERT TWO ROWS
IF SYSTEM FAILS OR SHUTDOWN THEN IT ALL DATA ARE AUTO SAVE. DATA ALWAYS REMAIN ON TABLE BECAUSE SQL IS ENABLED AUTO COMMIT ON.

# SCENERIO - 2

NOW -> SET AUTO COMMIT OFF USING START TRANSACTION; USING THIS HERE AFTER YOU MANUALLY SAVE THE DATA.
CREATE ONE TABLE
START TRANSACTION;
INSERT 1,2 ROWS
CREATE ANOTHER TABLE
INSERT 3,4 ROWS
IF SYSTEM FAILS OR SHUTDOWN HAPPEND -> ALL THE DATA AND TABLE CREATED SUCCESSFULLY. BECAUSE ONCE START THE TRANSACTION AUTO COMMIT OFF
                                       BUT BETWEEN INSERT WE DID DDL WHICH IS CREATE TABLE IT AUTOMATICALLY ON THE AUTO COMMIT OPTION.
                                       THATS WHY IF POWER FAILS THE DATA STILL REMAIN HERE.
                                    
# SCENERIO - 3

CREATE TABLE-1
START TRANSACTION;
INSERT 1,2 ROWS TO TABLE-1
SAVEPOINT QUARTERLY;

INSERT 3,4 TO TABLE-1
SAVEPOINT HALF;

INSERT 5,6 TO TABLE-1
SAVEPOINT DUMMY;

ROLLBACK TO HALF;
NOW -> SELECT * FROM TABLE-1 THEN IT GIVES THE SAVED DATA UPTO SAVEPOINT HALF; AFTER THAT WONT SAVE AND WONT HAVE IN THAT TABLE.
IF SYSTEM FAILS NO DATA SAVED BECAUSE NO COMMIT DONE AND NO DDL COMMANDS RUN.

# POINTS TO REMEMBER : ( REDO OPTION IS NOT AVAILABLE AND ALSO ONLY UPWARD DIRECTION )