# ------------------------------------------- DCL - GRANT AND REVOKE --------------------------------------------------

# NOTE : 

# 1. GRANT IS USED TO GIVE PRIVILEGES TO MYSQL USERS;
# 2. REVOKE IS USED TO REMOVE PRIVILEGES FROM USERS;

# SYNTAX :

# 1. GRANT PRIVILEGES ON DATABASE_NAME.TABLE_NAME TO USERNAME@HOST;
# 2. REVOKE PRIVILEGES ON DATABASE_NAME.TABLE_NAME FROM USERNAME@HOST;

# PRIVILEGES : ( SELECT, INSERT , UPDATE, DELETE, ALL PRIVILGES )

# EXAMPLE :

# 1. CREATE USER
					
                    CREATE USER 'VIJAY'@'LOCALHOST' IDENTIFIED BY '12345';
    
			# 2. GRANT
					
                    # 1. ALL PERMISSION TO ALL TABLES ON THAT DATABASE
						 GRANT ALL PRIVILEGES ON HR.* TO 'VIJAY'@'LOCALHOST';
                    
                    # 2. PARTICULAR PRIVILEGES TO ALL TABLES ON THAT DATABASE
						 GRANT SELECT ON MYSQL_TUTORIAL.* TO 'DUMMY'@'LOCALHOST';
                    
                    # 3. ALL PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 GRANT ALL PRIVILEGES ON HR.EMPLOYEES TO 'VIJAY'@'LOCALHOST';
                    
                    # 4. PARITICULAR PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 GRANT SELECT,INSERT ON HR.EMPLOYEES TO 'DUMMY'@'LOCALHOST';
			
            # 3. REVOKE
            
					# 1. REMOVE ALL PERMISSION TO ALL TABLES ON THAT DATABASE
						 REVOKE PRIVILEGES ON HR.* FROM 'VIJAY'@'LOCALHOST';
                    
                    # 2. REMOVE PARTICULAR PRIVILEGES TO ALL TABLES ON THAT DATABASE
						 REVOKE SELECT ON MYSQL_TUTORIAL.* FROM 'DUMMY'@'LOCALHOST';
                    
                    # 3. REMOVE ALL PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 REVOKE PRIVILEGES ON HR.EMPLOYEES FROM 'VIJAY'@'LOCALHOST';
                    
                    # 4. REMOVE PARITICULAR PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 REVOKE SELECT,INSERT ON HR.EMPLOYEES FROM 'DUMMY'@'LOCALHOST';
                         
			
            # 4. DISPLAY ALL THE USER
            
					SELECT USER,HOST FROM MYSQL.USER;
                    
			# 5. DELETE THE USER
            
					DROP USER IF EXISTS 'DUMMY'@'LOCALHOST';
                    
			# 6. CHANGE THE USER PASSWORD
            
					ALTER USER 'VIJAY'@'LOCALHOST' IDENTIFIED BY '1234';
                    
			# 7. APPLY CHANGES
            
					FLUSH PRIVILEGES;