# ------------------------------------------- DCL - GRANT AND REVOKE --------------------------------------------------

# NOTE : 

# 1. GRANT IS USED TO GIVE PRIVILEGES TO MYSQL USERS;
# 2. REVOKE IS USED TO REMOVE PRIVILEGES FROM USERS;

# SYNTAX :

# 1. GRANT PRIVILEGES ON DATABASE_NAME.TABLE_NAME TO USERNAME@HOST;
# 2. REVOKE PRIVILEGES ON DATABASE_NAME.TABLE_NAME FROM USERNAME@HOST;

# PRIVILEGES : ( SELECT, INSERT , UPDATE, DELETE, ALL PRIVILGES )

# EXAMPLE :

# 1. GRANT SELECT ON HR.EMPLOYEES TO AJAY@LOCALHOST;
# 2. GRANT ALL PRIVILEGES ON HR.EMPLOYEES TO SANJAY@LOCALHOST;
# 3. GRANT SELECT, INSERT ON HR.EMPLOYEES TO VIJAY@LOCALHOST;
# 4. REMOVE INSERT ON HR.EMPLOYEES FROM VIJAY@LOCALHOST;
# 5. REVOKE ALL PRIVILEGES ON HR.EMPLOYEES FROM SANJAY@LOCALHOST;

SELECT USER, HOST FROM MYSQL.USER; # TO DISPLAY ALL THE USERS DETAILS