# --------------------------------- SCD - SLOWLY CHANGING DIMENSION --------------------------------------------

# NOTE - IS A METHOD USED IN DATABASES TO TRACK AND PRESERVE HISTORICAL CHANGES IN DATA OVER TIME.

# USE CASES :
# 1. TRACK HISTORICAL DATA - WE WANT TO RETAIN OUR OLD VERSIONS OF OUR DATA FOR ACCURATE HISTORICAL ANALYSIS AND TRENDY REPORTING.
# 2. DATA ACCURACY 		   - ENSURES THE UPDATES WONT OVERRIDES THE PREVIOUS VALID DATA IN A WAY THAT CONFUSES ANALYSIS.
# 3. SIMPLIFY REPORTING    - MAKE IT EASIER FOR ANALYSIS TO QUERY THE DATA, KNOWING THEY CAN TRUST THE HISTORICAL RECORDS.

# TYPES :
# 1. TYPE 1 - OVERWRITE -> IT OVERWRITES THE OLD HISTORICAL DATA AND PREV RECORDS INCASE NOT IN USE THAT SITUATION.
# 2. TYPE 2 - ADD NEW RECORD -> IT ADDS A NEW RECORD INTO DATABASE WHICH CONTAINS THE OLD HISTORICAL DATA AS WELL AS NEW DATA.
# 3. TYPE 3 - ADD NEW ATTRIBUTE -> IT ADD NEW ATTRIBUTE INSTEAD OF ADDING NEW ROWS SIMPLY LIKE ADDING NEW COLUMN ONLY TO MAINTAIN HISTORICAL DATA JUST LIKE OLD ADDRESS,NEW ADDRESS.

CREATE TABLE PRODUCT_TYPE_1_SCD(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_TITLE VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100)
);

# TYPE - 1 - EXAMPLE - HERE WRONG INSERTED DATA AND AFTER THAT UPDATE THAT DATA BUT WE CANT SEE WHAT BEFORE THE DATA HAS SO IT COMES UNDER OVERWRITE CONCEPT.

INSERT INTO PRODUCT_TYPE_1_SCD VALUES
(101,'AMAZON ECO DOT 3RD GEN','SMART SPEAKERS','AMAZON');

SELECT * FROM PRODUCT_TYPE_1_SCD;

PRODUCT_ID  PRODUCT_TITLE           CATEGORY        BRAND
101	        AMAZON ECO DOT 3RD GEN	SMART SPEAKERS	AMAZON

UPDATE PRODUCT_TYPE_1_SCD
SET PRODUCT_TITLE = 'AMAZON ECHO DOT(3RD GEN)'
WHERE PRODUCT_ID = 101;

SELECT * FROM PRODUCT_TYPE_1_SCD;

PRODUCT_ID  PRODUCT_TITLE               CATEGORY        BRAND
101	        AMAZON ECHO DOT(3RD GEN)	SMART SPEAKERS	AMAZON

# TYPE - 2 - EXAMPLE - HERE WE JUST UPDATE THE DATA TO END THAT PROCESS AND INSERT NEW RECORD TO MAINTAIN WITH HISTORICAL ORDER.

CREATE TABLE SELLER_TYPE_2_SCD(
	SELLER_KEY INT PRIMARY KEY,
    SELLER_ID INT,
    SELLER_NAME VARCHAR(100),
    STORE_LOCATION VARCHAR(100),
    EFFECTIVE_DATE DATE,
    END_DATE DATE,
    IS_BOOLEAN BOOLEAN
);

INSERT INTO SELLER_TYPE_2_SCD VALUES
(1, 501, 'BEST SELLERS INC.','SEATTLE, WA','2022-01-01', NULL, TRUE);

SELECT * FROM SELLER_TYPE_2_SCD;

SELLER_KEY      SELLER_ID       SELLER_NAME         STORE_LOCATION          EFFECTIVE_DATE      END_DATE        IS_BOOLEAN
1	            501	            BEST SELLERS INC.	SEATTLE, WA	            2022-01-01		                    1

UPDATE SELLER_TYPE_2_SCD
SET
	END_DATE = '2023-01-15',
    IS_BOOLEAN = FALSE
WHERE SELLER_ID = 501;

INSERT INTO SELLER_TYPE_2_SCD VALUES
(2, 501, 'BEST SELLERS INC.','SEATTLE, WA','2023-01-15', NULL, TRUE);

SELECT * FROM SELLER_TYPE_2_SCD;

SELLER_KEY      SELLER_ID       SELLER_NAME         STORE_LOCATION          EFFECTIVE_DATE      END_DATE        IS_BOOLEAN
1	            501	            BEST SELLERS INC.	SEATTLE, WA	            2022-01-01		    2023-01-15      1
2	            501	            BEST SELLERS INC.	SEATTLE, WA	            2023-01-15		                    1

# TYPE - 3 - EXAMPLE

CREATE TABLE CATEGORY_TYPE_3_SCD(
	PRODUCT_ID INT PRIMARY KEY,
    PRODCUT_TITLE VARCHAR(100),
    CURRENT_CATEGORY VARCHAR(100),
    PREVIOUS_CATEGORY VARCHAR(100)
);

INSERT INTO CATEGORY_TYPE_3_SCD VALUES
(201, 'AMAZON FIRE TV STICK', 'STREAMING DEVICES', NULL);

SELECT * FROM CATEGORY_TYPE_3_SCD;

PRODUCT_ID      PRODCUT_TITLE           CURRENT_CATEGORY        PREVIOUS_CATEGORY
201	            AMAZON FIRE TV STICK	STREAMING DEVICES	

UPDATE CATEGORY_TYPE_3_SCD
SET
	PREVIOUS_CATEGORY = CURRENT_CATEGORY,
    CURRENT_CATEGORY = 'MEDIA PLAYERS'
WHERE PRODUCT_ID = 201;

SELECT * FROM CATEGORY_TYPE_3_SCD;

PRODUCT_ID      PRODCUT_TITLE           CURRENT_CATEGORY        PREVIOUS_CATEGORY
201	            AMAZON FIRE TV STICK	MEDIA PLAYERS	        STREAMING DEVICES