# --------------------------------- ACID RULE ----------------------------------------

# 1. ATOMICITY :

# FOR EXAMPLE : IF A USER GOING TO PURCHASE A NETFLIX ACCOUNT THEN THE USER PAY AT 199 TO NETFLIX.
#				THINK THAT THERE ARE 2 TRANSACTIONS ARE THERE. ONE IS DEBITED 199 FROM YOUR ACCOUNT AND ANOTHER ONE TRANSACTION IS 199 CREDITED TO NETFLIX.
# 				IF 199 DEBITED FROM USER ACCOUNT AND NETFLIX CREDITED FAILED THEN RETURNED 199 TO THE USER.
# 				SIMPLY SAYS THAT HERE IF ANY ONE OF THE TRANSACTION FAILED THEN REVERT THE ALL TRANSACTION THAT IS ATOMICITY.

# 2. CONSISTENCY - MAINTAIN

# FOR EXAMPLE : THINK ABOUT TWO TRADE ACCOUNT AND TOTAL VALUES IN YOUR ACCOUNT.
#				IF TRADE 1 ACCOUNT HAS $400 AND TRADE 2 HAS $ 500 THEN TOTAL SHOULD BE $900.
# 				IF GET $100 FROM TRADE 1 AND INVEST INTO TRADE 2 THEN ALSO MAINTAIN THE TOTAL WHICH IS $900.

# 3. ISOLATION :

# FOR EXAMPLE : THINK ABOUT TWO FRIENDS SEND MONEY TO YOUR ACCOUNT.
# 				IF THEY SEND AMOUNT AT A SAME TIME THEN THAT TWO TRANSACTION SHOULD NOT CRASH BETWEEN THEM.

# 4. DURABILITY : 

# FOR EXAMPLE : THINK ABOUT IRCTC PAGE.
# 				WHILE BOOKING TATKAL SOMETIMES WE PAID AMOUNT AND MONEY DEDUCTED FROM OUR ACCOUNT BUT SOMETIMES MAY DATABASE CRASH HAPPENED.
# 				THEN WHILE OPENING THE ACCOUNT THEN IT SHOULD GIVE YOUR TICKET AND SHOWN IT THAT IS HANDLED DURABILITY.