# -------------------------------------- STORED PROCEDURES -----------------------------------

# NOTE : A STORED PROCEDURE IS A PRECOMPILED SQL CODE BLOCK STORED IN THE DATABASE THAT CAN BE EXECUTED WHENEVER NEEDED.
# 		 IT IS ONE OF THE DATABASE OBJECTS.
#	     YOU SHOULD SELECT THE QUERY AND PROCEDURE AND CLICK THE THUNDER ICON TO EXECUTE IT WHILE USING PROCEDURE CONCEPT.
#		 IN,IN AND OUT,OUT,WITHOUT PARAMETER.

# SYNTAX :
/*
        DELIMITER $$
        CREATE PROCEDURE PROCEDURE_NAME(PARAMETERS)
            BEGIN
                SQL STATEMENT_1;
                SQL STATEMENT_2;
                ......
                SQL STATEMENT_N;
            END $$
*/

CREATE TABLE PROC_EXAMPLE(
	ID INT,
    NAME VARCHAR(25)
);

# 1. IN PARAMETER 

DELIMITER $$
CREATE PROCEDURE PROC_EXAMPLE(IN P_ID INT,P_NAME VARCHAR(25))
BEGIN
INSERT INTO PROC_EXAMPLE VALUES(P_ID,P_NAME);
END $$

CALL PROC_EXAMPLE(100,'VIJAY');
CALL PROC_EXAMPLE(200,'DHEEKSHA');

SELECT * FROM PROC_EXAMPLE;

DELIMITER $$
CREATE PROCEDURE UPDATE_PROC_EXAMPLE(IN P_ID INT,P_NAME VARCHAR(25))
BEGIN
UPDATE PROC_EXAMPLE
SET ID = P_ID
WHERE NAME = P_NAME;
END $$

CALL UPDATE_PROC_EXAMPLE(300,'VIJAY');

# 2. WITHOUT PARAMETER

DELIMITER $$
CREATE PROCEDURE TRUNCATE_PROC_EXAMPLE()
BEGIN
TRUNCATE TABLE PROC_EXAMPLE;
END $$

CALL TRUNCATE_PROC_EXAMPLE();

# 3. OUT PARAMETER

USE HR;

DELIMITER $$
CREATE PROCEDURE COUNT_EMPLOYEES(OUT CNT INT)
BEGIN
SELECT COUNT(*) INTO CNT FROM EMPLOYEES;
END $$

CALL COUNT_EMPLOYEES(@CNT);

SELECT @CNT AS CNT;

# 4. IN AND OUT PARAMETER

DELIMITER %%
CREATE PROCEDURE SUM_SALARY_EMPLOYEES(IN DEPT_ID INT,OUT SUM_SALARY INT)
BEGIN
SELECT SUM(SALARY) INTO SUM_SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = DEPT_ID;
END %%

CALL SUM_SALARY_EMPLOYEES(90,@SUM_SALARY);

SELECT @SUM_SALARY AS SUM_SALARY;   