CREATE TABLE MULTIPLE_WAYS : 

1. # NORMAL WAYS : 

    CREATE TABLE EMPLOYEE(
        EMP_NO INT PRIMARY KEY,
        EMP_NAME VARCHAR(100) NOT NULL,
        SALARY DECIMAL(10,2) NOT NULL,
        DOJ DATE NOT NULL
    );

2. # CTAS : ( CREATE TABLE AS SELECT - STATIC ) AND TABLE CREATED BASED ON THE RESULT OF QUERY. 
   # IT STORES DATA. STORESS AS A TABLE IN DATABASE.
   # IF WE DROP THE UNDERLYING TABLE THEN THIS CTAS TABLE STILL EXISTS WITH DATA BECAUSE IT STORES AS TABLE.

    CREATE TABLE HIGH_PAID_EMP AS 
    SELECT 
        EMP_NO,
        EMP_NAME,
        SALARY
    FROM EMPLOYEE
    WHERE SALARY >= 50000;

3. #TEMPORARY TABLE

    CREATE TEMPORARY TABLE TEMP_HIGH_PAID_EMP(
        EMP_NO INT PRIMARY KEY,
        SALARY DECIMAL(10,2)
    );

    INSERT INTO TEMP_HIGH_PAID_EMP
    SELECT 
        EMP_NO,
        SALARY
    FROM EMPLOYEE
    WHERE SALARY >= 50000;

4. #COMMON TABLE EXPRESSION

    # CTAS NOT USED
    WITH HIGH_SALARY_CTE AS (
        SELECT 
            EMP_NO,
            SALARY
        FROM EMPLOYEE
        WHERE SALARY >= 50000; 
    )
    CREATE TABLE HIGH_SALARY_EMP_VIA_CTE AS
    SELECT * FROM HIGH_SALARY_CTE;

    # CTAS USED
    CREATE TABLE HIGH_SALARY_EMP_VIA_CTE AS
    WITH HIGH_SALARY_CTE AS (
        SELECT EMP_NO, SALARY
        FROM EMPLOYEE
        WHERE SALARY >= 50000
    )
    SELECT * FROM HIGH_SALARY_CTE;