CREATE TABLE EMPLOYEES(
    EMP_NO INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL
);

# DDL (DATA DEFINITION LANGUAGE) :
    CREATE,
    ALTER,
    DROP,
    RENAME,
    TRUNCATE
    
# DESCRIBE TABLE
    
    DESC EMPLOYEES;

# ADD NEW COLUMN USING ALTER

    ALTER TABLE EMPLOYEES
    ADD EMAIL VARCHAR(100);

# REMOVE COLUMN FROM TABLE USING ALTER

    ALTER TABLE EMPLOYEES
    DROP COLUMN LAST_NAME;

# RENAME TABLE NAME USING ALTER

    ALTER TABLE EMPLOYEES
    RENAME TO EMPLOYEE;

# TRUNCATE TABLE

    TRUNCATE TABLE EMPLOYEE;

# DROP TABLE

    DROP TABLE EMPLOYEE;