CREATE TABLE EMPLOYEES(
    EMP_NO INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL
);

# DDL (DATA DEFINITION LANGUAGE) :
    CREATE,
    ALTER,
    DROP,
    RENAME,
    TRUNCATE
    
# DESCRIBE TABLE
    
    DESC EMPLOYEES;

# ADD NEW COLUMN USING ALTER

    ALTER TABLE EMPLOYEES
    ADD EMAIL VARCHAR(100);

# REMOVE COLUMN FROM TABLE USING ALTER

    ALTER TABLE EMPLOYEES
    DROP COLUMN LAST_NAME;

# RENAME TABLE NAME USING ALTER

    ALTER TABLE EMPLOYEES
    RENAME TO EMPLOYEE;

# TRUNCATE TABLE

    TRUNCATE TABLE EMPLOYEE;

# DROP TABLE

    DROP TABLE EMPLOYEE;

# --------------------------------- ADD ------------------------------

CREATE TABLE HINDUSTHAN(
ST_NAME TEXT(100),
PHONE INT);

SHOW TABLES;
DESC HINDUSTHAN;

# 1. ADD NEW COLUMN USING ADD
ALTER TABLE HINDUSTHAN
ADD COLUMN CITY VARCHAR(20);

# 2. ADD NEW COLUMN AT FIRST FIELD
ALTER TABLE HINDUSTHAN
ADD COLUMN ST_ID INT FIRST;

# 3. ADD NEW COLUMN IN BETWEEN
ALTER TABLE HINDUSTHAN
ADD COLUMN EMAIL VARCHAR(20) AFTER ST_NAME;

# 4. ADD NEW CONSTRAINTS FOR AN COLUMN
ALTER TABLE HINDUSTHAN
ADD CONSTRAINT PRIMARY KEY(ST_ID);

ALTER TABLE HINDUSTHAN
ADD CONSTRAINT UNIQUE(PHONE);

# ----------------------------------- CHANGE -------------------------------------------

DESC HINDUSTHAN;

# 1. CHANGE THE FIELD NAME USING ALTER

ALTER TABLE HINDUSTHAN
CHANGE ST_NAME FULLNAME TEXT(100);

# 2. CHANGE THE FIELD TYPE ALSO USING ALTER
ALTER TABLE HINDUSTHAN
CHANGE FULLNAME FULLNAME VARCHAR(30);

# 3. CHANGE THIE FIELD SIZE USING ALTER
ALTER TABLE HINDUSTHAN
CHANGE PHONE PHONE VARCHAR(10);

# ----------------------------------- MODIFY --------------------------------------------

DESC HINDUSTHAN;

# 1. MODIFY THE FIELD TYPE USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY PHONE INT;

# 2. MODIFY THE FIELD SIZE USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY EMAIL VARCHAR(40);

# 3. MODIFY THE CONSTRAINTS ALSO USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY EMAIL VARCHAR(40) NOT NULL;

# 4. MODIFY THE NULL ALSO USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY ST_ID INT NULL;

# ----------------------------------- DROP -----------------------------------------------

DESC HINDUSTHAN;

# 1. DROP COLUMN USING ALTER
ALTER TABLE HINDUSTHAN
DROP PHONE;

# 2. DROP CONSTRAINT USING ALTER
ALTER TABLE HINDUSTHAN
DROP PRIMARY KEY;