# ----------------------- MINIMAL KEY ---------------------------------

POINTS TO REMEMBER : 

    1. WE CAN CREATE COMPOSITE KEY USING MORE THAN ONE PRIMARK KEY WHICH IS NAME AS COMPOSITE KEY.
    2. FOR EX : PRIMARY KEY(STU_ID,C_ID,COURSE_NAME) -> NOT MINIMAL BECAUSE WITHOUT COURSE_NAME WE CAN ACHIEVE UNIQUENESS.
    3. FOR EX : PRIMARY KEY(STU_ID,C_ID) -> STILL WE CAN ACHIEVE UNIQUE. BECAUSE COURSE_NAME ALWAYS SAME FOR ALL SO INSTEAD WE CAN REMOVE FROM KEY.
    4. REMOVING UNWANTED COLUMN?(COURSE_NAME) IN AN PRIMARY KEY STILL WOULD LOSE THE UNIQUENESS WHICH IS KNOWN AS MINIMAL KEY.

# ----------------------- NATURAL KEY ----------------------------------

POINTS TO REMEMBER : ( JUST FOR THEORY PURPOSE ONLY NOT PRACTICAL )

    1. DEFAULTLY THAT FIELD VALUES SHOULD BE UNIQUE THAT FIELD KNOWN AS NATURAL KEY.
    2. FOR EX : AADHAR_CARD VARCHAR(25) NOT NULL -> IN THIS WE ARE NOT DECLARED AS PRIMARY KEY BUT IT WORKS AS PRIMARY KEY RIGHT BECAUSE IT ALWAYS HAS UNIQUE.

# ----------------------- SURROGATE KEY --------------------------------

 POINTS TO REMEMBER : ( JUST FOR THEORY PURPOSE ONLY NOT PRACTICAL )

    1. IF A TABLE HAS COURSE_NAME, END_DATE, START_DATE BUT IN THIS NO FIELD CAN SET PRIMARY KEY AT THAT TIME WE CAN CREATE ONE ID WITH AUTO_INCREMENT THAT KEY KNOWN AS SURROGATE KEY.
    2. COURSE_ID INT AUTO_INCREMENT -> IN THIS COURSE_ID KNOWN AS SURROGATE KEY.

# ----------------------- CANDIDATE KEY --------------------------------

POINTS TO REMEMBER : ( JUST FOR THEORY PURPOSE ONLY NOT PRACTICAL )

    1. ALL THE PRIMARY KEY AND COMPOSITE KEY ALSO A CANDIDATE KEY.
    2. EX : PRIMARY KEY(COURSE_ID) -> THIS PRIMARK KEY ALSO A CANDIDATE KEY. BECAUSE COURSE_ID GIVES UNIQUE THATS WHY.
    3. EX : PRIMARY KEY(COURSE_ID,COURSE_CODE) -> THIS COMPOSITE KEY ALSO A CANDIDATE KEY BECAUSE BOTH KEYS ARE GIVES UNIQUE.
    4. EX : PRIMARK KEY(COURSE_ID,COURSE_CODE,COURSE_NAME) -> IN THIS WITHOUT COURSE_NAME WE CAN ACHIEVE UNIQUE BUT IN THIS COURSE_NAME IS UNWANTED SO IN THIS COURSE_NAME IS NOT A CANDIDATE KEY.

# ----------------------- PRIMARY KEY ----------------------------------

POINTS TO REMEMBER :

    1. A COLUMN WHICH HAS UNIQUE REFERENCE THAT IS KNOWN AS PRIMARY KEY.
    2. FOR EX : COURSE_ID INT PRIMARK KEY - > COURSE_ID DOES NOT ALLOW DUPLICATE.
    3. COURSE_ID ALWAYS HAS VALUES BUT UNIQUE VALUES ONLY.
    4. IT DOESNOT ACCEPT NULL AND DUPLICATE VALUES.
    5. WE CAN USE THIS PRIMARY KEY AS ANOTHER TABLE FOREIGN KEY REFERENCE.

# ----------------------- UNIQUE KEY -----------------------------------

POINTS TO REMEMBER : 

    1. A COLUMN WHICH HAS UNIQUE REFERENCE THAT IS KNOWN AS UNIQUE KEY.
    2. FOR EX : EMAIL_ID VARCHAR(20) UNIQUE -> IN THIS EMAIL_ID SETS UNIQUE AND IT ACCEPT ONLY UNIQUE VALUES ONLY.
    3. ONLY DIFF BETWEEN PRIMARY KEY AND UNIQUE KEY IS IT ACCEPTS NULL VALUES BUT PRIMARY KEY DOESNOT ALLOW.

# ----------------------- SUPER KEY ------------------------------------

POINTS TO REMEMBER : ( JUST FOR THEORY PURPOSE ONLY NOT PRACTICAL )

    1. FOR EX : PRIMARY KEY(COURSE_ID) -> ALL PRIMARY KEYS ARE SUPER KEY.
    2. FOR EX : PRIMARY KEY(COURSE_ID,COURSE_CODE) -> ALL COMPOSITE KEYS ARE SUPER KEY.
    3. FOR EX : PRIMARK KEY(COURSE_ID,COURSE_CODE,COURSE_NAME) -> IT ALSO GIVE UNIQUE AFTER ALL COMBINED SO IT IS ALSO SUPER KEY SO ALL CANDIDATE KEYS ALSO SUPER KEY.

---------------------------------------------------------------------------------------------------------------------------------------------