# ------------------------------------ AGGREGATION --------------------------------------------

CREATE TABLE CUSTOMER(
    ID INT PRIMARY KEY,
    LOGIN_DEVICE VARCHAR(20),
    CUSTOMER_NAME VARCHAR(20),
    IP_ADDRESS VARCHAR(40),
    PRODUCT VARCHAR(20),
    AMOUNT DECIMAL(10,2),
    IS_PLACED BOOLEAN,
    IS_VIEWED BOOLEAN,
    TRANC_STATUS VARCHAR(20)
);	

INSERT INTO CUSTOMER VALUES
(1, 'Mobile', 'Ravi', '192.168.1.1', 'Laptop', 50000.00, TRUE, FALSE, 'Completed'),
(2, 'Desktop', 'Priya', '192.168.1.2', 'Smartphone', 20000.00, TRUE, TRUE, 'Completed'),
(3, 'Tablet', 'Arjun', '192.168.1.3', 'Headphones', 1500.00, FALSE, TRUE,'Failed'),
(4, 'Mobile', 'Heena', '192.168.1.4', 'Shoes', 2500.00, TRUE, FALSE, 'Completed'),
(5, 'Desktop', 'Kanthik', '192.168.1.5', 'Watch', 5000, TRUE, TRUE, 'Completed'),
(6, 'Mobile', 'Sowmya', '192.168.1.6', 'Tablet', 15000.00, TRUE, TRUE, 'Completed'),
(7, 'Tablet', 'Ramesh', '192.168.1.7', 'Smartphone', 25000.00, FALSE, TRUE, 'Failed'),
(8, 'Desktop', 'Divya', '192.168.1.8', 'Laptop', 60000.00, TRUE, FALSE, 'Completed'),
(9, 'Mobile', 'Arun', '192.168.1.9', 'Smartwatch', 12000.00, TRUE, TRUE, 'Completed'),
(10, 'Tablet', 'Deepa', '192.168.1.10', 'Laptop', 55000.00, FALSE, FALSE, 'Pending');

SELECT * FROM CUSTOMER;

# ------------------- 1. COUNT -------------------------
SELECT COUNT(*) FROM CUSTOMER; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED' AND PRODUCT = 'LAPTOP';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'PENDING' OR TRANC_STATUS = 'FAILED'; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS IN ('PENDING','FAILED');
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS NOT IN ('PENDING','FAILED');

# ----------------- 2. SUM ------------------------------
SELECT SUM(AMOUNT) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER;

NOTE :

    1. AS MEANS ALIAS NAME WHICH MEANS NICK_NAME.
    2. FOR EX : SELECT SUM(AMOUNT) FROM CUSTOMER -> IT DISPLAYS OUTPUT LIKE SUM(AMOUNT) FIELD_NAME.
    3. BUT SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER -> IT DISLAYS LIKE TOTAL_AMOUNT AS NEWLY AGGREGATED DATA.

# ----------------- 3. MIN ------------------------------
SELECT MIN(AMOUNT) AS MIN_TRANSACTION FROM CUSTOMER;

# ----------------- 4. MAX ------------------------------
SELECT MAX(AMOUNT) AS MAX_TRANSACTION FROM CUSTOMER;

# ----------------- 5. AVG ------------------------------
SELECT AVG(AMOUNT) AS AVG_TRANSACTION FROM CUSTOMER;

# ----------------- 6. GROUP BY -------------------------

NOTE : 
    1. GROUP BY WONT WORKS WITHOUT AGGREGATED FUNCTIONS.
    2. IN A SELECT QUERY IF WE USED COLUMN NAME , AGGREGATED FUNCTIONS MUST USE BY GROUP BY.
    3. IMPORTANT -> ONLY ONE ROW OUTPUT FOR A GROUP.

SELECT LOGIN_DEVICE,COUNT(LOGIN_DEVICE) AS DEVICE_WISE_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER
GROUP BY LOGIN_DEVICE;

# ----------------- 7. HAVING CLAUSE -------------------------

# IMP : WHERE FILTER THE ROWS AND RUNS AFTER THE FROM CLAUSE BUT HAVING WILL RUNS AFTER GROUP BY CLAUSE AND IT ALSO FILTER THE GROUP.

SELECT LOGIN_DEVICE,COUNT(LOGIN_DEVICE) AS DEVICE_WISE_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER
GROUP BY LOGIN_DEVICE
HAVING TOTAL_AMOUNT > 80000;

NOTE : 

    1. WHERE CONDITION USED ONLY FOR NON AGGREGATED COLUMN WHICH MEANS WHERE ONLY WORKS AT RAW FIELDS JUST LIKE AMOUNT,PRODUCT BUT NOT TOTAL_AMOUNT.
    2. HAVING CAN USED FOR AGGREGATED FIELDS WHERE CLAUSE USED FOR NON AGGREGATED FIELDS.
    3. IT CAN BE USED ONLY AFTER GROUP BY CLAUSE.
    4. IT ONLY USED BY AGGREGATED FIELDS ONLY.
    5. HAVING IS USED TO FILTER THE GROUP AND ITS WORKS WITH GROUP BY.
    6. WITHOUT GROUP BY IT WONT WORK. 
    7. IN WHERE CLAUSE AGGRAGATE FUNCTIONS WONT WORK BECAUSE ORDER OF EXECUTION THATS WHY WE WONT GIVE AGGREGATED FUNCTIONS ANSWERS INSIDE WHERE CLAUSE.