# ---------------------------- WHEN THEN -----------------------------------------

SELECT
CASE
	WHEN 8 > 10 THEN 'TRUE'
    ELSE 'FALSE'
END AS TEST;

SELECT
	CUSTOMER_NAME,AMOUNT,
	CASE
		WHEN AMOUNT > 20000 THEN 'RICH PEOPLE'
		WHEN AMOUNT BETWEEN 10000 AND 20000 THEN 'ORDINARY PEOPLE'
		WHEN AMOUNT < 10000 THEN 'ECONOMY PEOPLE'
	ELSE 'NOT APPLICABLE'
	END AS CATEGORY_AMOUNT_WISE
FROM CUSTOMER;

Ravi	50000.00	RICH PEOPLE
Priya	20000.00	ORDINARY PEOPLE
Arjun	1500.00	    ECONOMY PEOPLE
Heena	2500.00	    ECONOMY PEOPLE
Kanthik	5088.00	    ECONOMY PEOPLE
Sowmya	15000.00	ORDINARY PEOPLE
Ramesh	25000.00	RICH PEOPLE
Divya	60000.00	RICH PEOPLE
Arun	12000.00	ORDINARY PEOPLE
Deepa	55000.00	RICH PEOPLE

CREATE TABLE CUSTOMER_DUMMY(
	ID INT NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(25),
	PHONE VARCHAR(10),
	ADDRESS VARCHAR(20),
	AMOUNT VARCHAR(10)
);

INSERT INTO CUSTOMER_DUMMY VALUES
(1,'VIJAY','VIJAY@EXAMPLE.COM','9080457889','NELLAI','5000'),
(2,'SWATHI','NONE','1234556788','THANJAVUR','NONE'),
(3,'ARJUN','ARJUN@EXAMPLE.COM','NONE','BANGALORE','2500'),
(4,'DIYA','NONE','NONE','MUMBAI','1500'),
(5,'DHEEKSHA','DHEEKSHA@EXAMPLE.COM','9874683839','NONE','4000');

SELECT * FROM CUSTOMER_DUMMY;

SELECT
	NAME,
    CASE
		WHEN EMAIL = 'NONE' AND PHONE = 'NONE' THEN '999'
        WHEN PHONE = 'NONE' THEN EMAIL
	ELSE PHONE
    END AS CONTACT
FROM CUSTOMER_DUMMY;

( NOTE : ORDERING MATTER WHILE USING CASE STATEMENTS )

----------------------------- LIMIT USING IN SELECT STATEMENTS -----------------

( NOTE : PERFORMANCE IMPROVEMENT )

SELECT * FROM CUSTOMER_DUMMY LIMIT 3;