# ---------------- NULL HANDLING ------------------------------------

CREATE TABLE CUSTOMER_DUMMY(
ID INT NOT NULL,
NAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(25),
PHONE VARCHAR(10),
ADDRESS VARCHAR(20),
AMOUNT VARCHAR(10));

INSERT INTO CUSTOMER_DUMMY VALUES
(1,'VIJAY','VIJAY@EXAMPLE.COM','9080457889','NELLAI','5000'),
(2,'SWATHI', NULL,'1234556788','THANJAVUR',NULL),
(3,'ARJUN','ARJUN@EXAMPLE.COM',NULL,'BANGALORE','2500'),
(4,'DIYA',NULL,NULL,'MUMBAI','1500'),
(5,'DHEEKSHA','DHEEKSHA@EXAMPLE.COM','9874683839',NULL,'4000');

SELECT * FROM CUSTOMER_DUMMY;

1	VIJAY	    VIJAY@EXAMPLE.COM	    9080457889	NELLAI	    5000
2	SWATHI		                        1234556788	THANJAVUR	
3	ARJUN	    ARJUN@EXAMPLE.COM		            BANGALORE	2500
4	DIYA			                                MUMBAI	    1500
5	DHEEKSHA	DHEEKSHA@EXAMPLE.COM	9874683839		        4000

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE = NULL;

COUNT(*)
0

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE IS NULL;

COUNT(*)
2

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE IS NOT NULL;

COUNT(*)
3

POINTS TO REMEMBER :

    1. WE JUST INSERT AS NULL -> WE CANT DIRECTLY CHECK PHONE = NULL.
    2. IF WE INSERT AS 'NULL' -> THEN IT IS LOOK LIKE STRING THEN WE CAN CHECK PHONE = NULL.
    3. SO IF WE INSERT AS NULL -> THEN WE USED IS KEYWORD AND IS NOT.

SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NULL OR PHONE IS NULL OR ADDRESS IS NULL;

2	SWATHI		                        1234556788	THANJAVUR	
3	ARJUN	    ARJUN@EXAMPLE.COM		            BANGALORE	2500
4	DIYA			                                MUMBAI	    1500
5	DHEEKSHA	DHEEKSHA@EXAMPLE.COM	9874683839		        4000
    
SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NULL AND PHONE IS NULL;

4	DIYA			                                MUMBAI	    1500
    
SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NOT NULL AND PHONE IS NOT NULL AND ADDRESS IS NOT NULL;

1	VIJAY	    VIJAY@EXAMPLE.COM	    9080457889	NELLAI	    5000

# -------------------- COALESCE , IFNULL --------------------------------

SELECT ID,NAME,AMOUNT,COALESCE(AMOUNT,'0.00') FROM CUSTOMER_DUMMY;
SELECT ID,NAME,AMOUNT,IFNULL(AMOUNT,'0.00') FROM CUSTOMER_DUMMY;

1	VIJAY	    5000	5000
2	SWATHI		        0.00
3	ARJUN	    2500	2500
4	DIYA	    1500	1500
5	DHEEKSHA	4000	4000

POINTS TO REMEMBER ( COALESCE ):

    1. COALESCE IS USED FOR REPLACING NOT NULL VALUES FOR NULL VALUES.
    2. WE CAN USE MORE PARAMETERS AS WELL -> SELECT ID,NAME,AMOUNT,COALESCE(AMOUNT,'0.00',AMOUNT,'11') FROM CUSTOMER_DUMMY;
    3. BUT IT ALWAYS REPLACE FIRST NOT NULL VALUES.

POINTS TO REMEMBER ( IFNULL ): 

    1. IFNULL IS SAME AS COALESCE FOR REPLACING NOT NULL VALUES FOR NULL VALUES.
    2. WE USED TWO ARGUMENTS ONLY -> SELECT ID,NAME,AMOUNT,IFNULL(AMOUNT,'0.00') FROM CUSTOMER_DUMMY;