SHOW DATABASES;

CREATE DATABASE BESANT;

USE BESANT;

TRUNCATE TABLE EMPLOYEE;
TRUNCATE TABLE EDUCATION;
TRUNCATE TABLE DEPARTMENT;

DROP TABLE EMPLOYEE;
DROP TABLE EDUCATION;
DROP TABLE DEPARTMENT;

/* DEPARTMENT TABLE */

SHOW TABLES;

CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50) NOT NULL
);

/* EMPLOYEE TABLE */

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(50) UNIQUE,
EMP_EMAIL VARCHAR(50) UNIQUE,
EMP_PHONE VARCHAR(15) UNIQUE,
EMP_SALARY DECIMAL(10,2) CHECK (EMP_SALARY >= 10000),
DEPT_ID INT NULL,
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID) ON DELETE CASCADE
);

CREATE TABLE EDUCATION(
SCHOOL VARCHAR(50) NOT NULL,
COLLEGE VARCHAR(50) NOT NULL,
DEGREE VARCHAR(50) NOT NULL,
EMP_ID INT NOT NULL,
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE
);

ALTER TABLE EMPLOYEE MODIFY DEPT_ID INT NULL;

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM EDUCATION;

INSERT INTO DEPARTMENT VALUES
(100,'BACKEND'),
(200,'FRONTEND'),
(300,'SYSTEM_ADMIN'),   -- NO EMPLOYEES (Q3)
(400,'TESTING'),
(500,'MIDDLEWARE'),
(600,'DEVOPS'),         -- EXTRA DEPT FOR MULTIPLE EMPLOYEES (Q4,Q5,Q6)
(700,'SECURITY');       -- NO EMPLOYEES (Q3)

INSERT INTO EMPLOYEE VALUES
(1,'VIJAY','VIJAY@GMAIL.COM','9080245678',50000,100),
(2,'SWATHI','SWATHI@GMAIL.COM','9084723770',60000,200),
(3,'DEEKSHA','DEEKSHA@GMAIL.COM','1234567890',75000,500),
(4,'LAKSH','LAKSH@GMAIL.COM','0987654321',35000,400),
(5,'AKASH','AKASH@GMAIL.COM','9876543210',45000,600), -- DEVOPS
(6,'HARI','HARI@GMAIL.COM','9988776655',65000,600),  -- DEVOPS
(7,'VIGNESH','VIGNESH@GMAIL.COM','8877665544',30000,NULL), -- EMP WITHOUT DEPT (Q2)
(8,'PRIYA','PRIYA@GMAIL.COM','7766554433',90000,200); -- FRONTEND

INSERT INTO EDUCATION VALUES
('BHARATHIYAR GOVT','HINDUSTHAN','MCA',1),
('GIRLS HR SCHOOL','SASTRA','BE',2),
('JOHNS HR SCHOOL','SSN','BCA',4),
('CARMEL HR SCHOOL','IIT','MECH',5),  -- DEVOPS employee
('CARMEL HR SCHOOL','IIT','CSE',6),   -- DEVOPS employee
('DON BOSCO SCHOOL','ANNA UNIVERSITY','MBA',8);

/* REPORT - 1 */
/* QN - Combine three tables and return emp name, dept name, college, course (degree) */
SELECT 
    E.EMP_NAME AS EMPLOYEE_NAME,
    D.DEPT_NAME AS DEPARTMENT_NAME,
    ED.COLLEGE AS COLLEGE_NAME,
    ED.DEGREE  AS DEGREE_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D 
    ON E.DEPT_ID = D.DEPT_ID
JOIN EDUCATION ED 
    ON E.EMP_ID = ED.EMP_ID;
    
/* OUTPUT OF ABOVE QUERY
VIJAY	BACKEND		HINDUSTHAN		MCA
SWATHI	FRONTEND	SASTRA			BE
LAKSH	TESTING		SSN				BCA
AKASH	DEVOPS		IIT				MECH
HARI	DEVOPS		IIT				CSE
PRIYA	FRONTEND	ANNA UNIVERSITY	MBA
*/

/* QUERY - 2 */
/* QN - Find the employees for whom department is not assigned */

SELECT
	E.EMP_ID AS EMPLOYEE_ID,
    E.EMP_NAME AS EMPLOYEE_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.DEPT_ID IS NULL;

/*
7	VIGNESH
*/

/* QUERY - 3 */
/* QN - Find the departments where there are no employees */

SELECT 
	D.DEPT_ID,
    D.DEPT_NAME 
FROM DEPARTMENT D
LEFT JOIN EMPLOYEE E
	ON D.DEPT_ID = E.DEPT_ID
WHERE E.EMP_ID IS NULL;

/*
300	SYSTEM_ADMIN
700	SECURITY
*/

/* QUERY - 4 */
/* QN - Find the max salary of the employees department-wise */

SELECT 
	D.DEPT_NAME,
    MAX(E.EMP_SALARY) AS MAX_SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME;

/*
BACKEND		50000.00
FRONTEND	90000.00
TESTING		35000.00
MIDDLEWARE	75000.00
DEVOPS		65000.00
*/

/* QUERY - 5 */
/* QN - Find the total salary of the employee department-wise */

SELECT 
	D.DEPT_NAME,
    SUM(E.EMP_SALARY) AS TOTAL
FROM EMPLOYEE E
JOIN DEPARTMENT D
	ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID;

/*
BACKEND		50000.00
FRONTEND	150000.00
TESTING		35000.00
MIDDLEWARE	75000.00
DEVOPS		110000.00
*/

/* QUERY - 6 */
/* QN - Find the total employees department-wise */

SELECT
	D.DEPT_NAME,
    COUNT(E.EMP_ID) AS TOTAL_COUNT_OF_EMPLOYEES
FROM DEPARTMENT D
LEFT JOIN EMPLOYEE E
	ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME;

/*
BACKEND			1
FRONTEND		2
SYSTEM_ADMIN	0
TESTING			1
MIDDLEWARE		1
DEVOPS			2
SECURITY		0
*/

/* QUERY - 7 */
/* QN - Find the total employees of the college-wise */

SELECT
	ED.COLLEGE,
    COUNT(ED.EMP_ID) AS TOTAL_EMPLOYEES
FROM EDUCATION ED
JOIN EMPLOYEE E
	ON ED.EMP_ID = E.EMP_ID
GROUP BY ED.COLLEGE;

/*
HINDUSTHAN		1
SASTRA			1
SSN				1
IIT				2
ANNA UNIVERSITY	1
*/

/* QUERY - 8 */
/* QN - Find the total employees of the school-wise */
SELECT
	ED.SCHOOL,
    COUNT(ED.EMP_ID) AS TOTAL_EMPLOYEEs
FROM EDUCATION ED
JOIN EMPLOYEE E
	ON ED.EMP_ID = E.EMP_ID
GROUP BY ED.SCHOOL;

/*
BHARATHIYAR GOVT	1
GIRLS HR SCHOOL		1
JOHNS HR SCHOOL		1
CARMEL HR SCHOOL	2
DON BOSCO SCHOOL	1
*/

/* QUERY - 9 */
/* QN - create a user with give read permission only and after that logged that user and try to update and print what it shows */

CREATE USER 'dummy'@'localhost' IDENTIFIED BY '1234';
GRANT SELECT ON BESANT.* TO 'dummy'@'localhost';

/* QUERY - 10 */
/* QN - TRANSACTION, COMMIT, ROLLBACK, and SAVEPOINT */

START TRANSACTION;

UPDATE EMPLOYEE
SET EMP_SALARY = 80000
WHERE EMP_ID = 1;

SAVEPOINT SP1;

UPDATE EMPLOYEE 
SET EMP_SALARY = 75000 
WHERE EMP_ID = 2;

ROLLBACK TO SP1;

COMMIT;
