SHOW DATABASES;

CREATE DATABASE mysql_tutorial;

USE mysql_tutorial;

DROP DATABASE mysql_tutorial;

SHOW DATABASES;

SHOW TABLES;

CREATE TABLE TEST(
SNO INT,
SNAME VARCHAR(100));

SELECT * FROM TEST;

INSERT INTO TEST (SNO,SNAME)
VALUES (1,'VIJAY');

INSERT INTO TEST (SNO,SNAME)
VALUES (2,'SWATHI');

UPDATE TEST
SET SNAME = 'DEEKSHA'
WHERE SNO = 1;

INSERT INTO TEST (SNO,SNAME)
VALUES (3,'VIJAY');

DELETE FROM TEST
WHERE  SNAME = 'VIJAY';

TRUNCATE TABLE TEST;

DROP TABLE TEST;

# ALTER AND DDL CONCEPTS

ALTER TABLE TEST
ADD AGE INT;

DESC TEST;

ALTER TABLE TEST
DROP COLUMN AGE;

ALTER TABLE TEST
RENAME TO STUDENTS;

DESC STUDENTS;

SELECT * FROM STUDENTS;

# WHERE CLAUSE CONCEPTS

CREATE DATABASE UBER;

USE UBER;

CREATE TABLE RIDES(
    RIDE_ID INT,
    DRIVER_ID INT,
    RIDER_ID INT,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2)
);

INSERT INTO RIDES (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROP_LOCATION,RIDE_DATE,FARE)
VALUES
(1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,102,202,'BANGLORE','HYDERABAD','2025-12-29 10:00',800.00),
(3,103,203,'CHENNAI','MADURAI','2025-12-29 12:00:00',400.00),
(4,104,204,'COIMBATORE','CHENNAI','2025-12-29 14:00:00',600.00),
(5,101,205,'BANGLORE','COIMBATORE','2025-12-29 16:00:00',700.00);

SELECT * FROM RIDES;

SELECT * FROM RIDES
WHERE FARE > 500;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE DESC;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE ASC;

SELECT * FROM RIDES
WHERE 
	FARE > 500 AND
    DROP_LOCATION = 'CHENNAI'
ORDER BY FARE;

# --------------------------------- DDL - COMMANDS -------------------
# --------------------------------- ADD ------------------------------

CREATE TABLE HINDUSTHAN(
ST_NAME TEXT(100),
PHONE INT);

SHOW TABLES;
DESC HINDUSTHAN;

# 1. ADD NEW COLUMN USING ADD
ALTER TABLE HINDUSTHAN
ADD COLUMN CITY VARCHAR(20);

# 2. ADD NEW COLUMN AT FIRST FIELD
ALTER TABLE HINDUSTHAN
ADD COLUMN ST_ID INT FIRST;

# 3. ADD NEW COLUMN IN BETWEEN
ALTER TABLE HINDUSTHAN
ADD COLUMN EMAIL VARCHAR(20) AFTER ST_NAME;

# 4. ADD NEW CONSTRAINTS FOR AN COLUMN
ALTER TABLE HINDUSTHAN
ADD CONSTRAINT PRIMARY KEY(ST_ID);

ALTER TABLE HINDUSTHAN
ADD CONSTRAINT UNIQUE(PHONE);

# ----------------------------------- CHANGE -------------------------------------------

DESC HINDUSTHAN;

# 1. CHANGE THE FIELD NAME USING ALTER

ALTER TABLE HINDUSTHAN
CHANGE ST_NAME FULLNAME TEXT(100);

# 2. CHANGE THE FIELD TYPE ALSO USING ALTER
ALTER TABLE HINDUSTHAN
CHANGE FULLNAME FULLNAME VARCHAR(30);

# 3. CHANGE THIE FIELD SIZE USING ALTER
ALTER TABLE HINDUSTHAN
CHANGE PHONE PHONE VARCHAR(10);

# ----------------------------------- MODIFY --------------------------------------------

DESC HINDUSTHAN;

# 1. MODIFY THE FIELD TYPE USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY PHONE INT;

# 2. MODIFY THE FIELD SIZE USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY EMAIL VARCHAR(40);

# 3. MODIFY THE CONSTRAINTS ALSO USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY EMAIL VARCHAR(40) NOT NULL;

# 4. MODIFY THE NULL ALSO USING ALTER
ALTER TABLE HINDUSTHAN
MODIFY ST_ID INT NULL;

# ----------------------------------- DROP -----------------------------------------------

DESC HINDUSTHAN;

# 1. DROP COLUMN USING ALTER
ALTER TABLE HINDUSTHAN
DROP PHONE;

# 2. DROP CONSTRAINT USING ALTER
ALTER TABLE HINDUSTHAN
DROP PRIMARY KEY;

#------------------------------------ SQL-CONTRAINTS -------------------------------------
#------------------------------------ PRIMARY KEY ----------------------------------------
DROP TABLE RIDES;

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME NOT NULL,
    FARE DECIMAL(10,2) NOT NULL
);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

INSERT INTO RIDES
VALUES (2,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

#-----------------COMPOSITE PRIMARY KEY-----------------------------

CREATE TABLE RIDES(
    RIDE_ID INT,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(RIDE_ID,RIDER_ID)
);

DESC RIDES;

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

INSERT INTO RIDES
VALUES (1,101,202,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,202,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

#---------------------UNIQUE CONSTRAINTS-----------------------

DROP TABLE USERS;

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE
);

INSERT INTO USERS
VALUES(1,'user1@example.com');

SELECT * FROM USERS;

INSERT INTO USERS
VALUES(2,'user2@example.com');

INSERT INTO USERS
VALUES(3,NULL);

SELECT * FROM USERS;

INSERT INTO USERS
VALUES(2,'user2@example.com');

INSERT INTO USERS
VALUES(NULL,'abc@gmail.com');

INSERT INTO USERS
VALUES(4,'user2@example.com');

INSERT INTO USERS
VALUES(4,NULL);

#-----------------------NOT NULL CONSTRAINTS---------------------------------------- 

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2)
);

DESC RIDES;

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,NULL,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (3,101,201,NULL,'COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

# ---------------------------- CHECK CONTRAINTS ----------------------------
DROP TABLE RIDES;
CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0)
);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',-500.00);

# --------------------------- FOREIGN KEY CONTRAINTS --------------------------
# --------------------------- WITHOUT CASCADE ---------------------------------
DROP TABLE RIDES;
DROP TABLE DRIVERS;

CREATE TABLE DRIVERS(
DRIVER_ID INT PRIMARY KEY,
DRIVER_NAME VARCHAR(20) NOT NULL,
LICENSE_NUMBER VARCHAR(20) UNIQUE);

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0),
    FOREIGN KEY(DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID)
);

INSERT INTO DRIVERS VALUES
(101,'VIJAY','ABCD100'),
(102,'SWATHI','BZXP200');

SELECT * FROM DRIVERS;

INSERT INTO RIDES
VALUES (1,101,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,101,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',600.00),
(3,102,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',700.00);

SELECT * FROM RIDES;

# INSERT SCENERIO AS FOREIGN KEY
INSERT INTO RIDES(RIDE_ID,DRIVER_ID,PICKUP_LOCATION,DROP_LOCATION,RIDE_DATE,FARE)
VALUES(4,999,'MADURAI','NELLAI','2025-12-31 09:00:00',900.00);

# DELETE SCENERIO AS FOREIGN KEY
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;

# SOLUTION
DELETE FROM RIDES WHERE DRIVER_ID = 101;
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;

# ------------------------ WITH CASCADE ---------------------------

CREATE TABLE DRIVERS(
DRIVER_ID INT PRIMARY KEY,
DRIVER_NAME VARCHAR(20) NOT NULL,
LICENSE_NUMBER VARCHAR(20) UNIQUE);

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0),
    FOREIGN KEY(DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID) ON DELETE CASCADE
);

INSERT INTO DRIVERS VALUES
(101,'VIJAY','ABCD100'),
(102,'SWATHI','BZXP200');

INSERT INTO RIDES
VALUES (1,101,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,101,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',600.00),
(3,102,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',700.00);

DELETE FROM RIDES WHERE DRIVER_ID = 101;
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;
SELECT * FROM DRIVERS;
SELECT * FROM RIDES;

# ------------------------------------- INSTEAD OF DELETE A ROW WE CAN HIDE FROM IT USING FLAG --------------------

ALTER TABLE RIDES
ADD COLUMN IS_DELETE BOOLEAN DEFAULT FALSE;

SELECT * FROM RIDES;

UPDATE RIDES
SET
	IS_DELETE = TRUE
WHERE DRIVER_ID = 102;

# ---------------------------- DEFAULT CONSTRAINTS -------------------------------------

CREATE TABLE DUMMY(
SNO INT PRIMARY KEY,
SNAME VARCHAR(100) NOT NULL,
COUNTRY_CODE VARCHAR(20) DEFAULT 'IND'
);

DESC DUMMY;

INSERT INTO DUMMY(SNO,SNAME) VALUES(100,'VIJAY');
INSERT INTO DUMMY(SNO,SNAME,COUNTRY_CODE) VALUES(200,'SWATHI','USA');

SELECT * FROM DUMMY;

# ------------------------------------ AGGREGATION --------------------------------------------

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
LOGIN_DEVICE VARCHAR(20),
CUSTOMER_NAME VARCHAR(20),
IP_ADDRESS VARCHAR(40),
PRODUCT VARCHAR(20),
AMOUNT DECIMAL(10,2),
IS_PLACED BOOLEAN,
IS_VIEWED BOOLEAN,
TRANC_STATUS VARCHAR(20)
);	

INSERT INTO CUSTOMER VALUES
(1, 'Mobile', 'Ravi', '192.168.1.1', 'Laptop', 50000.00, TRUE, FALSE, 'Completed'),
(2, 'Desktop', 'Priya', '192.168.1.2', 'Smartphone', 20000.00, TRUE, TRUE, 'Completed'),
(3, 'Tablet', 'Arjun', '192.168.1.3', 'Headphones', 1500.00, FALSE, TRUE,'Failed'),
(4, 'Mobile', 'Heena', '192.168.1.4', 'Shoes', 2500.00, TRUE, FALSE, 'Completed'),
(5, 'Desktop', 'Kanthik', '192.168.1.5', 'Watch', 5000, TRUE, TRUE, 'Completed'),
(6, 'Mobile', 'Sowmya', '192.168.1.6', 'Tablet', 15000.00, TRUE, TRUE, 'Completed'),
(7, 'Tablet', 'Ramesh', '192.168.1.7', 'Smartphone', 25000.00, FALSE, TRUE, 'Failed'),
(8, 'Desktop', 'Divya', '192.168.1.8', 'Laptop', 60000.00, TRUE, FALSE, 'Completed'),
(9, 'Mobile', 'Arun', '192.168.1.9', 'Smartwatch', 12000.00, TRUE, TRUE, 'Completed'),
(10, 'Tablet', 'Deepa', '192.168.1.10', 'Laptop', 55000.00, FALSE, FALSE, 'Pending');

SELECT * FROM CUSTOMER;

# ------------------- 1. COUNT -------------------------
SELECT COUNT(*) FROM CUSTOMER; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED' AND PRODUCT = 'LAPTOP';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'PENDING' OR TRANC_STATUS = 'FAILED'; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS IN ('PENDING','FAILED');
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS NOT IN ('PENDING','FAILED');

# ----------------- 2. SUM ------------------------------
SELECT SUM(AMOUNT) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER;

# ----------------- 3. MIN ------------------------------
SELECT MIN(AMOUNT) AS MIN_TRANSACTION FROM CUSTOMER;

# ----------------- 4. MAX ------------------------------
SELECT MAX(AMOUNT) AS MAX_TRANSACTION FROM CUSTOMER;

# ----------------- 5. AVG ------------------------------
SELECT AVG(AMOUNT) AS AVG_TRANSACTION FROM CUSTOMER;

# ----------------- 6. GROUP BY -------------------------
SELECT LOGIN_DEVICE,COUNT(LOGIN_DEVICE) AS DEVICE_WISE_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER
GROUP BY LOGIN_DEVICE;

# ----------------- 7. HAVING CLAUSE -------------------------
SELECT LOGIN_DEVICE,COUNT(LOGIN_DEVICE) AS DEVICE_WISE_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER
GROUP BY LOGIN_DEVICE
HAVING TOTAL_AMOUNT > 80000;

# ---------------------------- WHEN THEN -----------------------------------------

SELECT
CASE
	WHEN 8 > 10 THEN 'TRUE'
    ELSE 'FALSE'
END AS TEST;

SELECT
	CUSTOMER_NAME,AMOUNT,
	CASE
		WHEN AMOUNT > 20000 THEN 'RICH PEOPLE'
		WHEN AMOUNT BETWEEN 10000 AND 20000 THEN 'ORDINARY PEOPLE'
		WHEN AMOUNT < 10000 THEN 'ECONOMY PEOPLE'
	ELSE 'NOT APPLICABLE'
	END AS CATEGORY_AMOUNT_WISE
FROM CUSTOMER;

CREATE TABLE CUSTOMER_DUMMY(
ID INT NOT NULL,
NAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(25),
PHONE VARCHAR(10),
ADDRESS VARCHAR(20),
AMOUNT VARCHAR(10));

INSERT INTO CUSTOMER_DUMMY VALUES
(1,'VIJAY','VIJAY@EXAMPLE.COM','9080457889','NELLAI','5000'),
(2,'SWATHI', NULL,'1234556788','THANJAVUR',NULL),
(3,'ARJUN','ARJUN@EXAMPLE.COM',NULL,'BANGALORE','2500'),
(4,'DIYA',NULL,NULL,'MUMBAI','1500'),
(5,'DHEEKSHA','DHEEKSHA@EXAMPLE.COM','9874683839',NULL,'4000');

SELECT * FROM CUSTOMER_DUMMY;

SELECT
	NAME,
    CASE
		WHEN EMAIL = 'NONE' AND PHONE = 'NONE' THEN '999'
        WHEN PHONE = 'NONE' THEN EMAIL
	ELSE PHONE
    END AS CONTACT
FROM CUSTOMER_DUMMY;

SELECT * FROM CUSTOMER_DUMMY LIMIT 3;

# ---------------- NULL HANDLING ------------------------------------

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE = NULL;

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE IS NULL;

SELECT COUNT(*) FROM CUSTOMER_DUMMY WHERE PHONE IS NOT NULL;

SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NULL OR PHONE IS NULL OR ADDRESS IS NULL;
    
SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NULL AND PHONE IS NULL;
    
SELECT * FROM CUSTOMER_DUMMY
WHERE
	EMAIL IS NOT NULL AND PHONE IS NOT NULL AND ADDRESS IS NOT NULL;
    
SELECT ID,NAME,AMOUNT,COALESCE(AMOUNT,'0.00') FROM CUSTOMER_DUMMY;
SELECT ID,NAME,AMOUNT,COALESCE(AMOUNT,'0.00',AMOUNT,'11') FROM CUSTOMER_DUMMY;
SELECT ID,NAME,AMOUNT,IFNULL(AMOUNT,'0.00') FROM CUSTOMER_DUMMY;

# --------------- STRING HANDLING ----------------------------------

SELECT * FROM CUSTOMERS;

SELECT CUSTOMER_NAME,
LENGTH(CUSTOMER_NAME) AS LENGTH_OF_CUSTOMER_NAME,
UPPER(CUSTOMER_NAME) AS CUSTOMER_NAME_IN_UPPERCASE,
LOWER(EMAIL) AS EMAIL_IN_LOWERCASE,
CONCAT(CUSTOMER_NAME,' - ',CITY) AS NAME_CITY_CONCAT,
SUBSTRING(CUSTOMER_NAME,1,6) AS SUBSTRING_CUSTOMER_NAME_1_6,
TRIM('     TRIMMING      ') AS TRIMMING,
LTRIM('     TRIMMING      ') AS LEFT_TRIMMING,
RTRIM('     TRIMMING      ') AS RIGHT_TRIMMING,
LPAD(CITY,10,'*') AS LEFT_PADDING,
RPAD(CITY,10,'#') AS RIGHT_PADDING,
REPLACE(CUSTOMER_NAME,' ','_') AS CUSTOMER_NAME_REPLACED,
INSTR(CUSTOMER_NAME,'a') AS POSITION_OF_A,
LEFT(CUSTOMER_NAME,5) AS FIRST_FIVE_CH_IN_CNAME,
RIGHT(CUSTOMER_NAME,3) AS LAST_THREE_CH_IN_CNAME,
REVERSE(CITY) AS REVERSED_CITY,
FORMAT(PHONE_NUMBER,3) AS FORMATTED_PHONE,
UPPER(REPLACE(CUSTOMER_NAME,' ','_')) AS INSIDE_UPPER_REPLACED
FROM CUSTOMERS;

SELECT 'VIRAT@GMAIL.COM' AS EMAIL,
	LEFT('VIRAT@GMAIL.COM',INSTR('VIRAT@GMAIL.COM','@')-1) AS FIRST_NAME,
    SUBSTR('VIRAT@GMAIL.COM',INSTR('VIRAT@GMAIL.COM','@')+1) AS DOMAIN;

# -------------------------- SUB QUERIES -----------------------------

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;
DROP TABLE ORDERS;
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    order_amount DECIMAL(10,2),
    order_date DATE,
    FOREIGN KEY(customer_id) REFERENCES CUSTOMERS(customer_id)
);

INSERT INTO orders (order_id, customer_id, order_amount, order_date) VALUES
(101, 1, 5000.00, '2025-01-01'),
(102, 2, 10000.00, '2025-01-02'),
(103, 3, 3000.00, '2025-01-03'),
(104, 4, 1500.00, '2025-01-04'),
(105, 1, 7000.00, '2025-01-05'),
(106, 5, 8000.00, '2025-01-06');

# WAY - 1 - SELECT
SELECT 
	CUSTOMER_NAME,
    (SELECT MAX(ORDER_AMOUNT) FROM ORDERS) AS MAX_ORDER_AMOUNT
FROM CUSTOMERS;

# WAY - 2 - WHERE _ IN 
SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE ID IN (SELECT DISTINCT CUSTOMER_ID FROM ORDERS WHERE ORDER_AMOUNT >= 5000);

# WAY - 3 -  WHERE _ EXISTS
SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE EXISTS (SELECT * FROM CUSTOMERS WHERE CITY = "CHENNAI");

SELECT CUSTOMER_NAME FROM CUSTOMERS
WHERE EXISTS (SELECT * FROM CUSTOMERS WHERE CITY = "NELLAI");

# WAY - 4 - WITHOUT JOIN
SELECT CUSTOMER_NAME,(SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) AS TOTAL_AMOUNT FROM CUSTOMERS;

# WAY - 5 - FROM
SELECT 
	LENGTH_OF_CUSTOMER_NAME,
    CUSTOMER_NAME_IN_UPPERCASE,
    EMAIL_IN_LOWERCASE,
    NAME_CITY_CONCAT,
    SUBSTRING_CUSTOMER_NAME_1_6,
    TRIMMING,
    LEFT_TRIMMING,
    RIGHT_TRIMMING,
    LEFT_PADDING,
    RIGHT_PADDING,
    CUSTOMER_NAME_REPLACED,
    POSITION_OF_A,
    FIRST_FIVE_CH_IN_CNAME,
    LAST_THREE_CH_IN_CNAME,
    REVERSED_CITY,
    FORMATTED_PHONE,
    INSIDE_UPPER_REPLACED
FROM (
	SELECT CUSTOMER_NAME,
	LENGTH(CUSTOMER_NAME) AS LENGTH_OF_CUSTOMER_NAME,
	UPPER(CUSTOMER_NAME) AS CUSTOMER_NAME_IN_UPPERCASE,
	LOWER(EMAIL) AS EMAIL_IN_LOWERCASE,
	CONCAT(CUSTOMER_NAME,' - ',CITY) AS NAME_CITY_CONCAT,
	SUBSTRING(CUSTOMER_NAME,1,6) AS SUBSTRING_CUSTOMER_NAME_1_6,
	TRIM('     TRIMMING      ') AS TRIMMING,
	LTRIM('     TRIMMING      ') AS LEFT_TRIMMING,
	RTRIM('     TRIMMING      ') AS RIGHT_TRIMMING,
	LPAD(CITY,10,'*') AS LEFT_PADDING,
	RPAD(CITY,10,'#') AS RIGHT_PADDING,
	REPLACE(CUSTOMER_NAME,' ','_') AS CUSTOMER_NAME_REPLACED,
	INSTR(CUSTOMER_NAME,'a') AS POSITION_OF_A,
	LEFT(CUSTOMER_NAME,5) AS FIRST_FIVE_CH_IN_CNAME,
	RIGHT(CUSTOMER_NAME,3) AS LAST_THREE_CH_IN_CNAME,
	REVERSE(CITY) AS REVERSED_CITY,
	FORMAT(PHONE_NUMBER,3) AS FORMATTED_PHONE,
	UPPER(REPLACE(CUSTOMER_NAME,' ','_')) AS INSIDE_UPPER_REPLACED
	FROM CUSTOMERS
    ) AS SUB_QUERY;
    
# WAY - 6 - WHEN

SELECT CUSTOMER_NAME,
CASE
	WHEN (SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) > (SELECT AVG(ORDER_AMOUNT) FROM ORDERS) THEN 'ABOVE_AVERAGE'
    ELSE 'BELOW AVERAGE'
END AS AMOUNT_CATEGORY
FROM CUSTOMERS;

SELECT CUSTOMER_NAME,LOWER(AMOUNT_CATEGORY) FROM (
SELECT CUSTOMER_NAME,
CASE
	WHEN (SELECT SUM(ORDER_AMOUNT) FROM ORDERS WHERE ORDERS.CUSTOMER_ID = CUSTOMERS.ID) > (SELECT AVG(ORDER_AMOUNT) FROM ORDERS) THEN 'ABOVE_AVERAGE'
    ELSE 'BELOW AVERAGE'
END AS AMOUNT_CATEGORY
FROM CUSTOMERS) AS AMOUNT_CATEGORY;

# -------------------------------- VIEWS -----------------------------------------------------

CREATE TABLE employees (
	employee_id INT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(100),
	hire_date DATE,
	job_title VARCHAR(50),
	salary DECIMAL (10, 2)
);

INSERT INTO employees (employee_id, first_name, last_name, email, hire_date, job_title, salary)
VALUES
(1, 'John', 'Doe', 'john.doe@example.com', '2022-05-01', 'Software Engineer', 85000.00),
(2, 'Jane', 'Smith', 'jane.smith@example.com', '2023-03-15', 'Data Scientist', 92000.00),
( 3, 'Alice', 'Johnson', 'alice.johnson@example.com', '2024-05-01', 'Engineer', 95000.00),
( 4, 'Mark', 'Taylor', 'mark.taylor@example.com', '2022-11-15', 'Manager', 100000.00),
(5, 'Gowtham', 'sb', 'mark.taylor@example.com', '2022-11-15', 'Data Engineer', 100000.00),
(6, 'Peter', 'sb', 'mark.taylor@example.com', '2022-11-15', 'Data Engineer', 120000.00);

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES WHERE SALARY >= 90000;
TRUNCATE TABLE EMPLOYEES;
DROP VIEW HIGH_EARNERS;

CREATE VIEW HIGH_EARNERS AS (SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES WHERE SALARY >= 90000);

SELECT * FROM HIGH_EARNERS;

INSERT INTO employees
VALUES (7, 'john', 'sb', 'mark.taylor@example.com', '2022-11-15', 'Data Engineer',120000.00);

# ----------------------------- JOIN TABLES --------------------------------------

CREATE TABLE RESTAURANTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    LOCATION VARCHAR(50)
);

INSERT INTO RESTAURANTS (ID, NAME, LOCATION) VALUES
(1, 'ABC Bistro', 'New York'),
(2, 'The Foodie', 'Los Angeles'),
(3, 'Tasty Treat', 'Chicago');

CREATE TABLE RESTAURANTS_ORDERS (
    ORDER_ID INT PRIMARY KEY,
    RESTAURANT_ID INT,
    ORDER_DATE DATE
);

INSERT INTO RESTAURANTS_ORDERS (ORDER_ID, RESTAURANT_ID, ORDER_DATE) VALUES
(1, 1, '2023-01-01'),
(2, 1, '2023-01-02'),
(3, 2, '2023-01-05'),
(4, 4, '2023-01-07');

# -------------------------------------- JOIN -> INNER JOIN --------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

# ------------------------------------- LEFT JOIN -------------------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
LEFT JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

# ------------------------------------- RIGHT JOIN -------------------------------------------------

SELECT
	R.NAME AS RESTAURANT_NAME,O.ORDER_DATE AS ORDER_DATE
FROM RESTAURANTS R
RIGHT JOIN RESTAURANTS_ORDERS O
ON R.ID = O.RESTAURANT_ID;

# ------------------------------------- SELF JOIN ------------------------------------------------

CREATE TABLE SELF_JOIN_TABLE(
	ID INT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
    MANAGER_ID INT NULL
);

INSERT INTO SELF_JOIN_TABLE
VALUES(1,'VIJAY',3),
(2,'SWATHI',3),
(3,'DHEEKSHA',NULL),
(4,'DIYA',3);

SELECT 
	F.NAME AS EMPLOYEE_NAME,
    S.NAME AS MANAGER_NAME
FROM SELF_JOIN_TABLE F
LEFT JOIN SELF_JOIN_TABLE S
ON F.MANAGER_ID = S.ID;

# ------------------------- WINDOW FUNCTION ----------------------------------------

CREATE TABLE SALES(
	TRANSACTION_ID INT,
    STORE VARCHAR(20),
    SALES_AMOUNT DECIMAL(10,2)
);

INSERT INTO SALES
VALUES(1,'A',100.00),(2,'A',200.00),(3,'A',150.00),(4,'B',250.00),(5,'B',300.00);

SELECT * FROM SALES;

# STORE WISE TRANSACTION

SELECT STORE,SUM(SALES_AMOUNT) AS AMOUNT FROM SALES
GROUP BY STORE;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER()
FROM SALES;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER() AS TOTAL
FROM SALES;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER(PARTITION BY STORE) AS TOTAL
FROM SALES;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT)
    OVER(PARTITION BY STORE ORDER BY TRANSACTION_ID) AS TOTAL
FROM SALES;

# ---------------------------------- RANKING WINDOW FUNCTIONS ---------------------------------------

# 1. ROW_NUMBER()

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER() AS ROW_NUM
FROM SALES;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER(ORDER BY SALES_AMOUNT DESC) AS ROW_NUM
FROM SALES;

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    ROW_NUMBER()
    OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT DESC) AS ROW_NUM
FROM SALES;

CREATE TABLE EMP_WINDOW(
	EMP_ID INT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(40),
    HIRE_DATE DATE
);

INSERT INTO EMP_WINDOW
VALUES
(1, 'ALICE', 'HR', '2020-05-01'),
(1, 'ALICE', 'HR', '2022-06-15'),
(2, 'BOB', 'IT', '2021-07-10'),
(3, 'CHARLIE', 'FINANCE', '2020-09-30'),
(3, 'CHARLIE', 'FINANCE', '2022-05-22');

SELECT * FROM EMP_WINDOW;

SELECT 
	EMP_ID,NAME,DEPARTMENT,HIRE_DATE,
    ROW_NUMBER() OVER() AS ROW_NUM
FROM EMP_WINDOW;

SELECT 
	EMP_ID,NAME,DEPARTMENT,HIRE_DATE,
    ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY HIRE_DATE ASC) AS ROW_NUM
FROM EMP_WINDOW;

WITH EMP_WINDOW_CTE AS 
(SELECT 
	EMP_ID,NAME,DEPARTMENT,HIRE_DATE,
    ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY HIRE_DATE ASC) AS ROW_NUM
FROM EMP_WINDOW)

SELECT EMP_ID,NAME,DEPARTMENT,HIRE_DATE FROM EMP_WINDOW_CTE WHERE ROW_NUM = 1;

# 2. RANK(), DENSE_RANK()

CREATE TABLE STUDENT_WINDOW(
	 STUDENT_ID INT,
     STUDENT_NAME VARCHAR(20),
     SCORE INT
);

INSERT INTO STUDENT_WINDOW
VALUES
(1, 'ALICE', 95),
(2, 'BOB', 90),
(3, 'CHARLIE', 95),
(4, 'DAVID', 85),
(5, 'EVA', 90);

SELECT
	STUDENT_ID, STUDENT_NAME, SCORE,
    RANK() OVER(ORDER BY SCORE DESC) AS RANK_OF_STUDENT
FROM STUDENT_WINDOW;

SELECT
	STUDENT_ID, STUDENT_NAME, SCORE,
    DENSE_RANK() OVER(ORDER BY SCORE DESC) AS RANK_OF_STUDENT
FROM STUDENT_WINDOW;

# 3. PERCENT_RANK()

SELECT
	STUDENT_ID, STUDENT_NAME, SCORE,
    RANK() OVER(ORDER BY SCORE DESC) AS RANK_OF_STUDENT,
    PERCENT_RANK() OVER(ORDER BY SCORE DESC) AS PERCENTAGE_RANK
FROM STUDENT_WINDOW;

# 4. NTILE()

CREATE TABLE EMPLOYEE_NTILE_WINDOW(
	EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(20),
    SALES_AMOUNT DECIMAL(10,2)
);

INSERT INTO EMPLOYEE_NTILE_WINDOW
VALUES
(1, 'Alice', 10000),
(2, 'Bob', 8500),
(3, 'Charlie', 7500),
(4, 'David', 6000),
(5, 'Eva', 11000),
(6, 'Frank', 4500),
(7, 'Grace', 3000),
(8, 'Hank', 4000),
(9, 'Ivy', 8000),
(10, 'Jack', 9500);

SELECT * FROM EMPLOYEE_NTILE_WINDOW;

SELECT
	EMPLOYEE_ID,EMPLOYEE_NAME,SALES_AMOUNT,
    NTILE(4) OVER(ORDER BY SALES_AMOUNT DESC) AS GROUP_NUMBER
FROM EMPLOYEE_NTILE_WINDOW;

# ---------------------------------- VALUE WINDOW FUNCTIONS ---------------------------------------

# 1. LAG()

CREATE TABLE EMPLOYEE_VALUE_WINDOW(
	EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(20),
    SALARY DECIMAL(10,2),
    YEAR VARCHAR(10)
);

INSERT INTO EMPLOYEE_VALUE_WINDOW
VALUES
(1, 'Alice', 5000.00, 2023),
(1, 'Alice', 5500.00, 2024),
(2, 'Bob', 4500.00, 2023),
(2, 'Bob', 4800.00, 2024),
(3, 'Charlie', 4000.00, 2023),
(3, 'Charlie', 4200.00, 2024),
(4, 'David', 4600.00, 2023),
(5,'Eva',5200.00,2023),
(5,'Eva',5400.00,2024);

SELECT 
	EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,YEAR,
    LAG(SALARY) OVER(PARTITION BY EMPLOYEE_ID ORDER BY YEAR) AS PREV_SALARY,
    SALARY - LAG(SALARY) OVER(PARTITION BY EMPLOYEE_ID ORDER BY YEAR) AS INCR_SALARY
FROM EMPLOYEE_VALUE_WINDOW;

# 2.LEAD()

CREATE TABLE PRODUCT_SALES (
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(50),
    SALEAMOUNT DECIMAL(10,2),
    SALEDATE DATE
);

INSERT INTO PRODUCT_SALES (PRODUCTID, PRODUCTNAME, SALEAMOUNT, SALEDATE) VALUES
(1, 'PRODUCT A', 500.00, '2025-01-01'),
(2, 'PRODUCT A', 400.00, '2025-02-02'),
(3, 'PRODUCT A', 700.00, '2025-03-01'),
(4, 'PRODUCT A', 500.00, '2025-04-02');

SELECT * FROM PRODUCT_SALES;

SELECT
	PRODUCTID,PRODUCTNAME,SALEDATE,SALEAMOUNT,
    LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE) AS NEXTMONTHSALE
FROM PRODUCT_SALES;

SELECT
	PRODUCTID,PRODUCTNAME,SALEDATE,SALEAMOUNT,
    LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE) AS NEXTMONTHSALE,
CASE
	WHEN LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE) - SALEAMOUNT IS NULL THEN SALEAMOUNT
    ELSE LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE) - SALEAMOUNT
    END AS SALESDIFF
FROM PRODUCT_SALES;

# 3. FIRST_VALUE()

CREATE TABLE EMPLOYEE_SALARY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    YEAR INT
);

INSERT INTO EMPLOYEE_SALARY (EMPLOYEEID, EMPLOYEENAME, SALARY, YEAR) VALUES
(1, 'ALICE', 5000.00, 2021),
(1, 'ALICE', 5500.00, 2022),
(1, 'ALICE', 6000.00, 2023),
(1, 'ALICE', 6500.00, 2024),
(1, 'ALICE', 7000.00, 2025),
(2, 'BOB', 4500.00, 2023),
(2, 'BOB', 4800.00, 2024),
(3, 'CHARLIE', 4000.00, 2023),
(3, 'CHARLIE', 4200.00, 2024),
(4, 'DAVID', 4600.00, 2023),
(4, 'DAVID', 4700.00, 2024),
(5, 'EVA', 5200.00, 2023),
(5, 'EVA', 5400.00, 2024);

SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY,
    FIRST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID) AS FIRST_SALARY
FROM EMPLOYEE_SALARY;

# 4. LAST_VALUE()

SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LATEST_SALARY
FROM EMPLOYEE_SALARY;

SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY AS YEAR_WISE_SALARY,
    FIRST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR) AS FIRST_SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LATEST_SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) - SALARY AS SALARY_DIFF_BY_CURRENT_TO_YEAR_WISE
FROM EMPLOYEE_SALARY;

# 5. NTH_VALUE()

CREATE TABLE EMPLOYEE_SALARY_NTH_WINDOW (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    SALARYDATE DATE
);

INSERT INTO EMPLOYEE_SALARY_NTH_WINDOW (EMPLOYEEID, EMPLOYEENAME, DEPARTMENT, SALARY, SALARYDATE) VALUES
(1, 'ALICE', 'HR', 5000.00, '2025-01-01'),
(7, 'GRACE', 'HR', 5500.00, '2025-01-07'),
(4, 'DAVID', 'HR', 6000.00, '2025-01-04'),
(6, 'FRANK', 'ENGINEERING', 6500.00, '2025-01-06'),
(2, 'BOB', 'ENGINEERING', 7000.00, '2025-01-02'),
(5, 'EVA', 'ENGINEERING', 7500.00, '2025-01-05'),
(3, 'CHARLIE', 'ENGINEERING', 8000.00, '2025-01-03'),
(8, 'HANK', 'ENGINEERING', 8500.00, '2025-01-08');

SELECT
	*,
    NTH_VALUE(SALARY,2) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS 2ND_LARGEST_SALARY_OF_THE_CURRENT_DEPARTMENT
FROM EMPLOYEE_SALARY_NTH_WINDOW;

# ------------------------- UNION AND UNION ALL -----------------------------------

CREATE TABLE EMPLOYEES_UNION (
	EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	POSITION VARCHAR(50),
	SALARY DECIMAL(10,2)
);

CREATE TABLE CONTRACTORS_UNION (
	CONTRACTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	POSITION VARCHAR(50),
	HOURLY_RATE DECIMAL (10,2)
);

INSERT INTO EMPLOYEES_UNION(FIRST_NAME,LAST_NAME,POSITION,SALARY)
VALUES
('ALICE', 'SMITH', 'DEVELOPER', 70000.00), ('BOB', 'JOHNSON', 'DEVELOPER', 75000.00),
('CHARLIE', 'LEE', 'MANAGER', 90000.00);

INSERT INTO CONTRACTORS_UNION (FIRST_NAME,LAST_NAME,POSITION,HOURLY_RATE)
VALUES
('DAVE', 'WILLIAMS', 'DEVELOPER', 40.00),
('EVE', 'BROWN', 'TESTER', 35.00),
('BOB', 'JOHNSON', 'DEVELOPER', 45.00);

SELECT * FROM EMPLOYEES_UNION
UNION ALL
SELECT * FROM CONTRACTORS_UNION;

SELECT * FROM EMPLOYEES_UNION
UNION
SELECT * FROM CONTRACTORS_UNION;

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
UNION ALL
SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
UNION
SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;

# ---------------------------------- INDEX - EXPLAIN ------------------------------

# ----------------------------------- WITH USING ----------------------------------

CREATE TABLE CUSTOMERS_INDEX(
	CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL
);

CREATE INDEX IDX_EMAIL ON CUSTOMERS_INDEX(EMAIL);

INSERT INTO CUSTOMERS_INDEX(FIRST_NAME, LAST_NAME, EMAIL, CITY)
VALUES
(
'John', 'Doe', 'john@example.com', 'New York'),
('Jane', 'Smith', 'jane.smith@example.com', 'Los Angeles'),
('Michael', 'Brown', 'michael.brown@example.com', 'Chicago'),
('Emily', 'Johnson', 'emily.johnson@example.com', 'Houston'),
('Robert', 'Green', 'robert.green@example.com', 'Phoenix');

SELECT * FROM CUSTOMERS_INDEX WHERE EMAIL = 'john@example.com';

EXPLAIN
SELECT * FROM CUSTOMERS_INDEX WHERE EMAIL = 'john@example.com';

EXPLAIN ANALYZE
SELECT * FROM CUSTOMERS_INDEX WHERE EMAIL = 'john@example.com';

EXPLAIN FORMAT = JSON
SELECT * FROM CUSTOMERS_INDEX WHERE EMAIL = 'john@example.com';

# ------------------------------- WITHOUT USING INDEX -----------------------

CREATE TABLE CUSTOMERS_INDEX_1(
	CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL
);

INSERT INTO CUSTOMERS_INDEX_1(FIRST_NAME, LAST_NAME, EMAIL, CITY)
VALUES
(
'John', 'Doe', 'john@example.com', 'New York'),
('Jane', 'Smith', 'jane.smith@example.com', 'Los Angeles'),
('Michael', 'Brown', 'michael.brown@example.com', 'Chicago'),
('Emily', 'Johnson', 'emily.johnson@example.com', 'Houston'),
('Robert', 'Green', 'robert.green@example.com', 'Phoenix');

EXPLAIN
SELECT * FROM CUSTOMERS_INDEX_1 WHERE EMAIL = 'john@example.com';

EXPLAIN ANALYZE
SELECT * FROM CUSTOMERS_INDEX_1 WHERE EMAIL = 'john@example.com';

EXPLAIN FORMAT = JSON
SELECT * FROM CUSTOMERS_INDEX_1 WHERE EMAIL = 'john@example.com';

# ------------------------------- PARTITION ----------------------------------------
# ------------------------------- 1. RANGE PARTITION -------------------------------

CREATE TABLE ORDERS_PARTITION (
	ORDER_ID INT AUTO_INCREMENT,
	ORDER_DATE DATE NOT NULL,
	CUSTOMER_NAME VARCHAR(50),
	AMOUNT DECIMAL(10,2),
    PRIMARY KEY(ORDER_ID,ORDER_DATE)
)
PARTITION BY RANGE (YEAR (ORDER_DATE)) (
	PARTITION PARTITION_BEFORE_2020 VALUES LESS THAN (2020),
	PARTITION PARTITION_2020 VALUES LESS THAN (2021),
	PARTITION PARTITION_2021 VALUES LESS THAN (2022),
	PARTITION PARTITION_2022 VALUES LESS THAN (2023),
	PARTITION PARTITION_AFTER_2022 VALUES LESS THAN MAXVALUE
);

INSERT INTO ORDERS_PARTITION(ORDER_DATE,CUSTOMER_NAME,AMOUNT)
VALUES
('2019-05-10', 'ALICE', 100.00),
('2020-01-15', 'BOB', 200.50),
('2020-12-01', 'CHARLIE', 300.00),
('2021-07-20', 'DIANA', 150.75),
('2022-03-02', 'EDWARD', 500.00),
('2025-06-18', 'FUTUREMAN', 9999.99);

SELECT 
	PARTITION_NAME,PARTITION_METHOD,PARTITION_EXPRESSION,SUBPARTITION_METHOD,SUBPARTITION_EXPRESSION
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_SCHEMA = 'MYSQL_TUTORIAL' AND TABLE_NAME = 'ORDERS_PARTITION';

SHOW CREATE TABLE ORDERS_PARTITION;

SELECT * FROM ORDERS_PARTITION WHERE YEAR(ORDER_DATE) = 2021;

EXPLAIN FORMAT = JSON
SELECT * FROM ORDERS_PARTITION WHERE YEAR(ORDER_DATE) = 2021;

SELECT * FROM ORDERS_PARTITION WHERE ORDER_DATE = '2021-07-20';

EXPLAIN FORMAT = JSON
SELECT * FROM ORDERS_PARTITION WHERE ORDER_DATE = '2021-07-20';

# ----------------------------- 2. LIST PARTITION -------------------------

CREATE TABLE EMPLOYEES_LIST_PARTITION(
	EMPLOYEE_ID INT AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DEPARTMENT VARCHAR(50),
    PRIMARY KEY(EMPLOYEE_ID,DEPARTMENT)
)
PARTITION BY LIST COLUMNS(DEPARTMENT) (
	PARTITION SALES_TEAM VALUES IN ('SALES'),
	PARTITION HR_TEAM VALUES IN ('HR'),
	PARTITION ENG_TEAM VALUES IN ('ENGINEERING', 'DEVOPS'),
	PARTITION OTHERS_TEAM VALUES IN ('FINANCE', 'MARKETING', 'OPERATIONS')
);

INSERT INTO EMPLOYEES_LIST_PARTITION(FIRST_NAME, LAST_NAME, DEPARTMENT)
VALUES
('ALICE', 'SMITH', 'SALES'),
('BOB', 'JOHNSON', 'HR'),
('CHARLIE', 'LEE', 'ENGINEERING'),
('DIANA', 'LOPEZ', 'DEVOPS'),
('EVE','TURNER','Marketing');

EXPLAIN FORMAT = JSON
SELECT * FROM EMPLOYEES_LIST_PARTITION WHERE FIRST_NAME = 'BOB';

SELECT * FROM EMPLOYEES_LIST_PARTITION WHERE DEPARTMENT IN ('SALES','DEVOPS');

EXPLAIN FORMAT = JSON
SELECT * FROM EMPLOYEES_LIST_PARTITION WHERE DEPARTMENT IN ('SALES','DEVOPS');

# --------------------------------- HASH PARTITIONS ---------------------------------

CREATE TABLE SENSOR_DATA_HASH_PARTITION(
	SENSOR_ID INT NOT NULL,
    READING_TIME DATETIME NOT NULL,
    READING_VALUE DECIMAL(10,2),
    PRIMARY KEY(SENSOR_ID, READING_TIME)
)
PARTITION BY HASH(SENSOR_ID) PARTITIONS 2;

INSERT INTO SENSOR_DATA_HASH_PARTITION (SENSOR_ID, READING_TIME, READING_VALUE)
VALUES
(101, '2025-01-01 10:00:00', 23.50),
(102, '2025-01-01 10:05:00', 24.10),
(103, '2025-01-01 10:10:00', 22.75),
(104, '2025-01-01 10:15:00', 25.00),
(105, '2025-01-01 10:20:00', 20.00),
(106, '2025-01-01 10:25:00', 21.60);

EXPLAIN FORMAT = JSON
SELECT * FROM SENSOR_DATA_HASH_PARTITION WHERE SENSOR_ID = 101;

EXPLAIN FORMAT = JSON
SELECT * FROM SENSOR_DATA_HASH_PARTITION WHERE SENSOR_ID = 102;

# ---------------------------- DATE TIME --------------------------------------

CREATE TABLE EVENTS_DATE_TIME(
	EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_NAME VARCHAR(100),
    EVENT_DATE DATETIME,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EVENTS_DATE_TIME (EVENT_NAME, EVENT_DATE)
VALUES
('TEAM MEETING', '2025-01-15 10:30:00'),
('CONFERENCE', '2025-02-10 09:00:00'),
('ONLINE WEBINAR', '2025-03-05 15:45:00'),
('WORKSHOP', '2025-03-20 13:30:00');

SELECT * FROM EVENTS_DATE_TIME;

# 1. YEAR,DATE,DAY EXTRACTION

SELECT EVENT_NAME,EVENT_DATE,YEAR(EVENT_DATE) AS EVENT_YEAR,DATE(EVENT_DATE) AS EVENT_DATE,DAY(EVENT_DATE) AS EVENT_DAY FROM EVENTS_DATE_TIME;

# 2. ADDING OR SUBTRACTING N DAYS

SELECT EVENT_NAME,EVENT_DATE,EVENT_DATE + INTERVAL 30 DAY AS 30_DAYS_AFTER, EVENT_DATE - INTERVAL 30 DAY AS 30_DAYS_BEFORE FROM EVENTS_DATE_TIME;

# 3. FORMATING DATES

SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%W, %w') AS DAY_AND_COUNT_OF_THE_DAY FROM EVENTS_DATE_TIME;
SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%Y, %y') AS FULL_YEAR_AND_LAST_TWO FROM EVENTS_DATE_TIME;
SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%e') AS DAY_DISPLAY FROM EVENTS_DATE_TIME;
SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%M, %m') AS MONTH_NAME_AND_MONTH_NUMBER FROM EVENTS_DATE_TIME;
SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%d, %D') AS DAY_AND_DAY_WITH_TH FROM EVENTS_DATE_TIME;
SELECT EVENT_DATE,DATE_FORMAT(EVENT_DATE,'%b') AS ABBREVATION_OF_MONTH FROM EVENTS_DATE_TIME;

SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT(EVENT_DATE, '%W, %D %M %Y') AS FORMATTED_DATE FROM EVENTS_DATE_TIME;

# 4. TIME FORMATTING

SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT(EVENT_DATE, '%H') AS HOUR_ONLY FROM EVENTS_DATE_TIME;
SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT(EVENT_DATE, '%i') AS MINUTES_ONLY FROM EVENTS_DATE_TIME;
SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT('2025-01-15 10:30:22', '%s, %S') AS SECONDS_ONLY FROM EVENTS_DATE_TIME;
SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT('2025-01-15 13:30:22', '%p') AS AM_PM FROM EVENTS_DATE_TIME;
SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT(EVENT_DATE, '%H:%i %p') AS 24_HOURS_TIME_FORMAT FROM EVENTS_DATE_TIME;
SELECT EVENT_NAME,EVENT_DATE, DATE_FORMAT(EVENT_DATE, '%h:%i %p') AS 12_HOURS_TIME_FORMAT FROM EVENTS_DATE_TIME;

SELECT EVENT_NAME,EVENT_DATE,DATE_FORMAT(EVENT_DATE, '%W, %D %M %Y, %h:%i %p') AS EVENT_DATE_TIME_FORMATTED FROM EVENTS_DATE_TIME;

# ------------------------------------------ REGEX ---------------------------------------------------

CREATE TABLE REGEX_SAMPLES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    SAMPLE_TEXT VARCHAR(100)
);

INSERT INTO REGEX_SAMPLES(SAMPLE_TEXT) VALUES
('APPLE'),('BANANA'),('CHERRY'),('DATE'),('ELDERBERRY'),('FIG'),('GRAPE'),('HONEYDEW'),('RUNNING'),('123ABC');

SELECT * FROM REGEX_SAMPLES;

SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^A';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'ING$';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '(.)\\1';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Za-z]+$';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^.{5}$';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^(APPLE|BANANA)$';
SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]{3}[A-Z]+$';

CREATE TABLE REGEX_DEMO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	full_name VARCHAR(50),
	phone VARCHAR(25),
	email VARCHAR(100),
	date_col VARCHAR(10),
	status VARCHAR(20),
	sku VARCHAR(20),
	username VARCHAR(30),
	notes VARCHAR(100)
);

INSERT INTO REGEX_DEMO (full_name, phone, email, date_col, status, sku, username, notes)
VALUES
('John Smith','123-456-7890','john@example.com','2025-02-07','pending','ABCD','johnsmith','Ships to CA'),
('Alice Johnson','(987) 654-3210','alice@@example.net','2025-02-07','inactive','SKU-123','alice','NY location'),
('Bob Williams','+1-555-123-4567','bob@sample.org','20250207','complete','1SKU','bob123','Shipping to CA'),
('Mary 1 White','(123) 123-4567','mary123@example.com','2025-13-31','PENDING','abc-999','mary_white','Something about CA or'),
('Mark-Spencer','1234567890','mark@example.com','2024-11-02','active','SKU-9999','mark','Random note'),
('Jane O''Connor','1987-654-3210','jane.o.connor@example.org','2024-12-31','inactive','ABCDE','JaneO','Contains CA or NY'),
('Invalid Mail','000-000-0000','invalid@@example..com','2023-01-15','inactive','XYZeee','invalid','Double and dots'),
('NoSpacesHere','+12-345-678-9012','nospaces@example.co','2025-02-07','pending','SKU999','NoSpaces','Ends with.co domain');

SELECT * FROM REGEX_DEMO;

SELECT ID,FULL_NAME,DATE_COL FROM REGEX_DEMO WHERE DATE_COL REGEXP '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$'; # DISPLAYING ONLY VALID DATE FORMAT ('YYYY-MM-DD')
SELECT ID,FULL_NAME FROM REGEX_DEMO WHERE FULL_NAME REGEXP '^[A-Za-z ]+$'; # MATCHES NAMES CONTAINING ONLY LETTERS AND SPACES

# ------------------------------------------- TCL - COMMIT AND ROLLBACK AND SAVEPOINT ----------------------------------------------

# NOTE : TCL - TRANSACTION CONTROL LANGUAGE -> MANAGE TRANSACTION WITHING THE DATABASE.

# POINTS TO REMEMBER : 
# 1. COMMIT    - TO SAVE TRANSACTION PERMANENTLY
# 2. ROLLBACK  - TO UNDO TRANSACTION
# 3. SAVEPOINT - TO SET A POINT WITHTIN A TRANSACTION TO WHICH YOU CAN ROLL BACK

# ------------------------------------------- DCL - GRANT AND REVOKE --------------------------------------------------

# NOTE : 

# 1. GRANT IS USED TO GIVE PRIVILEGES TO MYSQL USERS;
# 2. REVOKE IS USED TO REMOVE PRIVILEGES FROM USERS;

# SYNTAX :

# 1. GRANT PRIVILEGES ON DATABASE_NAME.TABLE_NAME TO USERNAME@HOST;
# 2. REVOKE PRIVILEGES ON DATABASE_NAME.TABLE_NAME FROM USERNAME@HOST;

# PRIVILEGES : ( SELECT, INSERT , UPDATE, DELETE, ALL PRIVILGES )

# EXAMPLE :

# 1. GRANT SELECT ON HR.EMPLOYEES TO AJAY@LOCALHOST;
# 2. GRANT ALL PRIVILEGES ON HR.EMPLOYEES TO SANJAY@LOCALHOST;
# 3. GRANT SELECT, INSERT ON HR.EMPLOYEES TO VIJAY@LOCALHOST;
# 4. REMOVE INSERT ON HR.EMPLOYEES FROM VIJAY@LOCALHOST;
# 5. REVOKE ALL PRIVILEGES ON HR.EMPLOYEES FROM SANJAY@LOCALHOST;

SELECT USER, HOST FROM MYSQL.USER; # TO DISPLAY ALL THE USERS DETAILS

# ------------------------------- NORMALIZATION ----------------------------------

# NOTES : 

# 1. NORMALIZATION IN SQL IS A SYSTAMATIC PROCESS OF ORGANIZING COLUMNS AND TABLES AND REDUCES THE REDUNDANCY AND IMPROVES THE INTEGRITY.
# TYPES - 1NF,2NF,3NF

# 1. 1NF - FIRST NORMAL FORM
#	     - EVERY COLUMN HOLDS ONLY ATOMIC VALUES(SINGLE VALUES) AND THAT THERE ARE NO REPEATING GROUPS.
#		 - SIMPLY SAYS THAT EACH FIELD CONTAINS SINGLE PIECE OF DATA.

# 2. 2NF - SECOND NORMAL FORM
#		 - IT REQUIRES THE TABLE SHOULD SATISFY THE 1NF.
#		 - ALL NON KEY COLUMNS FULLY FUNCTIONALLY DEPENDENT ON THE ENTIRE PRIMARY KEY.
# 		 - SIMPLY SAYS THAT TO REMOVE PARTIAL DEPENDENCY.

# 3. 3NF - THIRD NORMAL FORM
#		 - IT MUST SATISFY 2NF.
# 		 - NO TRANSITIVE DEPENDENCY.
#		 - SIMPLY SAYS THAT TO REMOVE TRANSITIVE DEPENDENCY WHERE A NON KEY COLUMN DEPENDS ON ANOTHER NON KEY COLUMN.

# --------------------------------- SCD - SLOWLY CHANGING DIMENSION --------------------------------------------

# NOTE - IS A METHOD USED IN DATABASES TO TRACK AND PRESERVE HISTORICAL CHANGES IN DATA OVER TIME.

# USE CASES :
# 1. TRACK HISTORICAL DATA - WE WANT TO RETAIN OUR OLD VERSIONS OF OUR DATA FOR ACCURATE HISTORICAL ANALYSIS AND TRENDY REPORTING.
# 2. DATA ACCURACY 		   - ENSURES THE UPDATES WONT OVERRIDES THE PREVIOUS VALID DATA IN A WAY THAT CONFUSES ANALYSIS.
# 3. SIMPLIFY REPORTING    - MAKE IT EASIER FOR ANALYSIS TO QUERY THE DATA, KNOWING THEY CAN TRUST THE HISTORICAL RECORDS.

# TYPES :
# 1. TYPE 1 - OVERWRITE -> IT OVERWRITES THE OLD HISTORICAL DATA AND PREV RECORDS INCASE NOT IN USE THAT SITUATION.
# 2. TYPE 2 - ADD NEW RECORD -> IT ADDS A NEW RECORD INTO DATABASE WHICH CONTAINS THE OLD HISTORICAL DATA AS WELL AS NEW DATA.
# 3. TYPE 3 - ADD NEW ATTRIBUTE -> IT ADD NEW ATTRIBUTE INSTEAD OF ADDING NEW ROWS SIMPLY LIKE ADDING NEW COLUMN ONLY TO MAINTAIN HISTORICAL DATA JUST LIKE OLD ADDRESS,NEW ADDRESS.

CREATE TABLE PRODUCT_TYPE_1_SCD(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_TITLE VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100)
);

# TYPE - 1 - EXAMPLE - HERE WRONG INSERTED DATA AND AFTER THAT UPDATE THAT DATA BUT WE CANT SEE WHAT BEFORE THE DATA HAS SO IT COMES UNDER OVERWRITE CONCEPT.

INSERT INTO PRODUCT_TYPE_1_SCD VALUES
(101,'AMAZON ECO DOT 3RD GEN','SMART SPEAKERS','AMAZON');

SELECT * FROM PRODUCT_TYPE_1_SCD;

UPDATE PRODUCT_TYPE_1_SCD
SET PRODUCT_TITLE = 'AMAZON ECHO DOT(3RD GEN)'
WHERE PRODUCT_ID = 101;

# TYPE - 2 - EXAMPLE - HERE WE JUST UPDATE THE DATA TO END THAT PROCESS AND INSERT NEW RECORD TO MAINTAIN WITH HISTORICAL ORDER.

CREATE TABLE SELLER_TYPE_2_SCD(
	SELLER_KEY INT PRIMARY KEY,
    SELLER_ID INT,
    SELLER_NAME VARCHAR(100),
    STORE_LOCATION VARCHAR(100),
    EFFECTIVE_DATE DATE,
    END_DATE DATE,
    IS_BOOLEAN BOOLEAN
);

INSERT INTO SELLER_TYPE_2_SCD VALUES
(1, 501, 'BEST SELLERS INC.','SEATTLE, WA','2022-01-01', NULL, TRUE);

SELECT * FROM SELLER_TYPE_2_SCD;

UPDATE SELLER_TYPE_2_SCD
SET
	END_DATE = '2023-01-15',
    IS_BOOLEAN = FALSE
WHERE SELLER_ID = 501;

INSERT INTO SELLER_TYPE_2_SCD VALUES
(2, 501, 'BEST SELLERS INC.','SEATTLE, WA','2023-01-15', NULL, TRUE);

# TYPE - 3 - EXAMPLE

CREATE TABLE CATEGORY_TYPE_3_SCD(
	PRODUCT_ID INT PRIMARY KEY,
    PRODCUT_TITLE VARCHAR(100),
    CURRENT_CATEGORY VARCHAR(100),
    PREVIOUS_CATEGORY VARCHAR(100)
);

INSERT INTO CATEGORY_TYPE_3_SCD VALUES
(201, 'AMAZON FIRE TV STICK', 'STREAMING DEVICES', NULL);

SELECT * FROM CATEGORY_TYPE_3_SCD;

UPDATE CATEGORY_TYPE_3_SCD
SET
	PREVIOUS_CATEGORY = CURRENT_CATEGORY,
    CURRENT_CATEGORY = 'MEDIA PLAYERS'
WHERE PRODUCT_ID = 201;
