SHOW DATABASES;

CREATE DATABASE mysql_tutorial;

USE mysql_tutorial;

DROP DATABASE mysql_tutorial;

SHOW DATABASES;

SHOW TABLES;

CREATE TABLE TEST(
SNO INT,
SNAME VARCHAR(100));

SELECT * FROM TEST;

INSERT INTO TEST (SNO,SNAME)
VALUES (1,'VIJAY');

INSERT INTO TEST (SNO,SNAME)
VALUES (2,'SWATHI');

UPDATE TEST
SET SNAME = 'DEEKSHA'
WHERE SNO = 1;

INSERT INTO TEST (SNO,SNAME)
VALUES (3,'VIJAY');

DELETE FROM TEST
WHERE  SNAME = 'VIJAY';

TRUNCATE TABLE TEST;

DROP TABLE TEST;

# ALTER AND DDL CONCEPTS

ALTER TABLE TEST
ADD AGE INT;

DESC TEST;

ALTER TABLE TEST
DROP COLUMN AGE;

ALTER TABLE TEST
RENAME TO STUDENTS;

DESC STUDENTS;

SELECT * FROM STUDENTS;

# WHERE CLAUSE CONCEPTS

CREATE DATABASE UBER;

USE UBER;

CREATE TABLE RIDES(
    RIDE_ID INT,
    DRIVER_ID INT,
    RIDER_ID INT,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2)
);

INSERT INTO RIDES (RIDE_ID,DRIVER_ID,RIDER_ID,PICKUP_LOCATION,DROP_LOCATION,RIDE_DATE,FARE)
VALUES
(1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,102,202,'BANGLORE','HYDERABAD','2025-12-29 10:00',800.00),
(3,103,203,'CHENNAI','MADURAI','2025-12-29 12:00:00',400.00),
(4,104,204,'COIMBATORE','CHENNAI','2025-12-29 14:00:00',600.00),
(5,101,205,'BANGLORE','COIMBATORE','2025-12-29 16:00:00',700.00);

SELECT * FROM RIDES;

SELECT * FROM RIDES
WHERE FARE > 500;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE DESC;

SELECT * FROM RIDES
WHERE FARE > 500
ORDER BY FARE ASC;

SELECT * FROM RIDES
WHERE 
	FARE > 500 AND
    DROP_LOCATION = 'CHENNAI'
ORDER BY FARE;

#------------------------------------SQL-CONTRAINTS-------------------------------------
#------------------------------------PRIMARY KEY----------------------------------------
DROP TABLE RIDES;

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME NOT NULL,
    FARE DECIMAL(10,2) NOT NULL
);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

INSERT INTO RIDES
VALUES (2,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

#-----------------COMPOSITE PRIMARY KEY-----------------------------

CREATE TABLE RIDES(
    RIDE_ID INT,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(RIDE_ID,RIDER_ID)
);

DESC RIDES;

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

INSERT INTO RIDES
VALUES (1,101,202,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,202,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

#---------------------UNIQUE CONSTRAINTS-----------------------

DROP TABLE USERS;

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE
);

INSERT INTO USERS
VALUES(1,'user1@example.com');

SELECT * FROM USERS;

INSERT INTO USERS
VALUES(2,'user2@example.com');

INSERT INTO USERS
VALUES(3,NULL);

SELECT * FROM USERS;

INSERT INTO USERS
VALUES(2,'user2@example.com');

INSERT INTO USERS
VALUES(NULL,'abc@gmail.com');

INSERT INTO USERS
VALUES(4,'user2@example.com');

INSERT INTO USERS
VALUES(4,NULL);

#-----------------------NOT NULL CONSTRAINTS---------------------------------------- 

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2)
);

DESC RIDES;

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,NULL,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (3,101,201,NULL,'COIMBATORE','2025-12-29 08:00:00',500.00);

SELECT * FROM RIDES;

# ---------------------------- CHECK CONTRAINTS ----------------------------
DROP TABLE RIDES;
CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0)
);

INSERT INTO RIDES
VALUES (1,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00);

INSERT INTO RIDES
VALUES (2,101,201,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',-500.00);

# --------------------------- FOREIGN KEY CONTRAINTS --------------------------
# --------------------------- WITHOUT CASCADE ---------------------------------
DROP TABLE RIDES;
DROP TABLE DRIVERS;

CREATE TABLE DRIVERS(
DRIVER_ID INT PRIMARY KEY,
DRIVER_NAME VARCHAR(20) NOT NULL,
LICENSE_NUMBER VARCHAR(20) UNIQUE);

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0),
    FOREIGN KEY(DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID)
);

INSERT INTO DRIVERS VALUES
(101,'VIJAY','ABCD100'),
(102,'SWATHI','BZXP200');

SELECT * FROM DRIVERS;

INSERT INTO RIDES
VALUES (1,101,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,101,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',600.00),
(3,102,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',700.00);

SELECT * FROM RIDES;

# INSERT SCENERIO AS FOREIGN KEY
INSERT INTO RIDES(RIDE_ID,DRIVER_ID,PICKUP_LOCATION,DROP_LOCATION,RIDE_DATE,FARE)
VALUES(4,999,'MADURAI','NELLAI','2025-12-31 09:00:00',900.00);

# DELETE SCENERIO AS FOREIGN KEY
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;

# SOLUTION
DELETE FROM RIDES WHERE DRIVER_ID = 101;
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;

# ------------------------ WITH CASCADE ---------------------------

CREATE TABLE DRIVERS(
DRIVER_ID INT PRIMARY KEY,
DRIVER_NAME VARCHAR(20) NOT NULL,
LICENSE_NUMBER VARCHAR(20) UNIQUE);

CREATE TABLE RIDES(
    RIDE_ID INT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    PICKUP_LOCATION VARCHAR(100) NOT NULL,
    DROP_LOCATION VARCHAR(100) NOT NULL,
    RIDE_DATE DATETIME,
    FARE DECIMAL(10,2) CHECK (FARE > 0),
    FOREIGN KEY(DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID) ON DELETE CASCADE
);

INSERT INTO DRIVERS VALUES
(101,'VIJAY','ABCD100'),
(102,'SWATHI','BZXP200');

INSERT INTO RIDES
VALUES (1,101,'CHENNAI','COIMBATORE','2025-12-29 08:00:00',500.00),
(2,101,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',600.00),
(3,102,'COIMBATORE','CHENNAI','2025-12-30 09:00:00',700.00);

DELETE FROM RIDES WHERE DRIVER_ID = 101;
DELETE FROM DRIVERS WHERE DRIVER_ID = 101;
SELECT * FROM DRIVERS;
SELECT * FROM RIDES;

# ------------------------------------- INSTEAD OF DELETE A ROW WE CAN HIDE FROM IT USING FLAG --------------------

ALTER TABLE RIDES
ADD COLUMN IS_DELETE BOOLEAN DEFAULT FALSE;

SELECT * FROM RIDES;

UPDATE RIDES
SET
	IS_DELETE = TRUE
WHERE DRIVER_ID = 102;

# ---------------------------- DEFAULT CONSTRAINTS -------------------------------------

CREATE TABLE DUMMY
( SNO INT PRIMARY KEY,
SNAME VARCHAR(100) NOT NULL,
COUNTRY_CODE VARCHAR(20) DEFAULT 'IND');

DESC DUMMY;

INSERT INTO DUMMY(SNO,SNAME) VALUES(100,'VIJAY');
INSERT INTO DUMMY(SNO,SNAME,COUNTRY_CODE) VALUES(200,'SWATHI','USA');

SELECT * FROM DUMMY;

# ------------------------------------ AGGREGATION --------------------------------------------

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
LOGIN_DEVICE VARCHAR(20),
CUSTOMER_NAME VARCHAR(20),
IP_ADDRESS VARCHAR(40),
PRODUCT VARCHAR(20),
AMOUNT DECIMAL(10,2),
IS_PLACED BOOLEAN,
IS_VIEWED BOOLEAN,
TRANC_STATUS VARCHAR(20)
);	

INSERT INTO CUSTOMER VALUES
(1, 'Mobile', 'Ravi', '192.168.1.1', 'Laptop', 50000.00, TRUE, FALSE, 'Completed'),
(2, 'Desktop', 'Priya', '192.168.1.2', 'Smartphone', 20000.00, TRUE, TRUE, 'Completed'),
(3, 'Tablet', 'Arjun', '192.168.1.3', 'Headphones', 1500.00, FALSE, TRUE,'Failed'),
(4, 'Mobile', 'Heena', '192.168.1.4', 'Shoes', 2500.00, TRUE, FALSE, 'Completed'),
(5, 'Desktop', 'Kanthik', '192.168.1.5', 'Watch', 5000, TRUE, TRUE, 'Completed'),
(6, 'Mobile', 'Sowmya', '192.168.1.6', 'Tablet', 15000.00, TRUE, TRUE, 'Completed'),
(7, 'Tablet', 'Ramesh', '192.168.1.7', 'Smartphone', 25000.00, FALSE, TRUE, 'Failed'),
(8, 'Desktop', 'Divya', '192.168.1.8', 'Laptop', 60000.00, TRUE, FALSE, 'Completed'),
(9, 'Mobile', 'Arun', '192.168.1.9', 'Smartwatch', 12000.00, TRUE, TRUE, 'Completed'),
(10, 'Tablet', 'Deepa', '192.168.1.10', 'Laptop', 55000.00, FALSE, FALSE, 'Pending');

SELECT * FROM CUSTOMER;

# ------------------- 1. COUNT -------------------------

SELECT COUNT(*) FROM CUSTOMER; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED' AND PRODUCT = 'LAPTOP';
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS = 'PENDING' OR TRANC_STATUS = 'FAILED'; 
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS IN ('PENDING','FAILED');
SELECT COUNT(*) FROM CUSTOMER WHERE TRANC_STATUS NOT IN ('PENDING','FAILED');

# ----------------- 2. SUM ------------------------------

SELECT SUM(AMOUNT) FROM CUSTOMER WHERE TRANC_STATUS = 'COMPLETED';