SHOW DATABASES;

CREATE DATABASE SKILLSYNC;

USE SKILLSYNC;

SHOW TABLES;

# DROP TABLE userdetails;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE auth_user;
TRUNCATE TABLE userdetails;

SET FOREIGN_KEY_CHECKS = 1;
DESC userdetails;

# USE THESE TWO COMMANDS FOR ONCE TABLE WAS RE MIGRATED AFTER DELETE THE MIGRATIONS FILES AS WELL DROP THE TABLE MANUALLY AFTER THAT PLEASE DO THIS
DELETE FROM django_migrations WHERE app='UserDetails';

# SELECT QUERIES FOR ALL TABLES
SELECT * FROM USERDETAILS;	
SELECT * FROM VIJAY_TABLE;
SELECT * FROM COURSES;
SELECT * FROM CLASSES;
SELECT * FROM STAFF_ASSIGNMENTS;
SELECT * FROM NOTIFICATIONS;
SELECT * FROM STUDENT_ENROLLMENTS;
SELECT * FROM STUDENT_ATTENDANCE;
SELECT * FROM STAFF_LEAVE_REQUEST;
SELECT * FROM STUDENT_LEAVE_REQUEST;