# 1. DISPLAY DATABASES NAMES

		SHOW DATABASES;

# 2. CREATE DATABASE

		CREATE DATABASE SQL_CHEATSHEET;

# 3. CHOOSE DATABASE

		USE SQL_CHEATSHEET;

# 4. DISPLAY TABLES UNDER DATABASES

		SHOW TABLES;

# 5. TYPES OF COMMANDS - DDL,DML,DCL,TCL,DQL
	
	# 1. DDL - CREATE, ALTER, DROP, RENAME
    
			# 1. CREATE TABLE
				# WAY - 1
				
						CREATE TABLE SIMPLE_TABLE(
							ID INT,
							NAME VARCHAR(20),
							DESCRIPTION TEXT(50),
							DOB DATETIME,
							PHONE VARCHAR(20),
							AMOUNT DECIMAL(10,2),
							CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
						);
						
				# WAY - 2 - TEMPORARY TABLE
				
						CREATE TEMPORARY TABLE TEMP_TABLE(
							ID INT,
							NAME VARCHAR(20),
							AMOUNT DECIMAL(10,2)
						);
				
				# WAY - 3 - CTAS
				
						CREATE TABLE CTAS_TABLE AS 
							SELECT * FROM SIMPLE_TABLE;
				
				# WAY - 4 - CTE
				
						WITH CTE_TABLE AS (
							SELECT * FROM SIMPLE_TABLE
						)
						SELECT ID,NAME FROM CTE_TABLE;
            
			# 2. ALTER - ADD,MODIFY,CHANGE,DROP,RENAME
    
				# 1. ADD
				
						# ADD AT FIRST
						ALTER TABLE SIMPLE_TABLE
						ADD COLUMN ST_ID INT FIRST;
						
						# BETWEEN
						ALTER TABLE SIMPLE_TABLE
						ADD COLUMN EMAIL VARCHAR(20) AFTER DOB;
						
						# ENDING - DEFAULT - IF NOTHING GIVEN IT ADD AT LAST
						ALTER TABLE SIMPLE_TABLE
						ADD COLUMN STATUS BOOLEAN DEFAULT FALSE;
						
						# KEY ADDING USING ADD
						ALTER TABLE SIMPLE_TABLE
						ADD CONSTRAINT UNIQUE(EMAIL);
						
						ALTER TABLE SIMPLE_TABLE
						ADD CONSTRAINT PRIMARY KEY(ID);
						
				# 2. MODIFY
				
						# FIELD NAME CHANGE
						ALTER TABLE SIMPLE_TABLE
						CHANGE DESCRIPTION ADDRESS VARCHAR(20);
						
						# FIELD TYPE CHANGE
						ALTER TABLE SIMPLE_TABLE
						CHANGE ADDRESS ADDRESS TEXT(50);
						
						# FIELD SIZE CHANGE
						ALTER TABLE SIMPLE_TABLE
						CHANGE ADDRESS ADDRESS TEXT(20);
						
				# 3. MODIFY
				
						# FIELD TYPE MODIFY
						ALTER TABLE SIMPLE_TABLE
						MODIFY ADDRESS VARCHAR(20);
						
						# FIELD SIZE MODIFY
						ALTER TABLE SIMPLE_TABLE
						MODIFY ADDRESS VARCHAR(25);
						
						# MODIFY THE CONSTAINT
						ALTER TABLE SIMPLE_TABLE
						MODIFY EMAIL VARCHAR(20) NOT NULL;
						
				# 4. DROP

						# DROP THE FIELD
						ALTER TABLE SIMPLE_TABLE
						DROP COLUMN ST_ID;
						
						# DROP THE CONSTRAINT
						ALTER TABLE SIMPLE_TABLE
						DROP CONSTRAINT EMAIL;
						
				# 5. RENAME
				
						# RENAME TABLE NAME
						ALTER TABLE SIMPLE_TABLE
						RENAME TO SAMPLE_TABLE;
                    
			# 3. RENAME TABLE
					
				# 1. RENAME TABLE NAME
                     RENAME TABLE SAMPLE_TABLE TO SIMPLE_TABLE;
                    
			# 4. DROP TABLE
            
				# 1. DROP TABLE
					 DROP TABLE SIMPLE_TABLE;
                    
	# 2. DML - INSERT,UPDATE,DELETE,TRUNCATE
    
			# 1. INSERT COMMAND
            
					INSERT INTO SIMPLE_TABLE (ID,NAME,ADDRESS,DOB,EMAIL,PHONE,AMOUNT)
					VALUES
						(1,'VIJAY','NELLAI','2000-11-13 11:00:09','ABDVIJAY@GMAIL.COM','+91 9000457089','5000.00'),
						(2,'SWATHI','THANJAVUR','2000-04-07 11:00:09','SWATHI@GMAIL.COM','+91 7263242348','8000.00');
                        
					INSERT INTO SIMPLE_TABLE (ID,NAME,ADDRESS,DOB,EMAIL,PHONE,AMOUNT)
					VALUES
						(3,'DUMMY','MADURAI','2000-11-13 11:00:09','ABDVIJAY@GMAIL.COM','+91 9000457089','5000.00');
                
			# 2. UPDATE RECORD
            
					UPDATE SIMPLE_TABLE
                    SET
						PHONE = '+91 6380712345',
                        AMOUNT = '12000.00'
					WHERE
						ID = 2 AND AMOUNT = '8000.00';
                        
			# 3. DELETE RECORD
            
					DELETE FROM SIMPLE_TABLE
                    WHERE ID = 3;
                    
			# 4. TRUNCATE TABLE
            
					TRUNCATE TABLE SIMPLE_TABLE;
                    
			# 5. DROP TABLE
					
                    DROP TABLE SIMPLE_TABLE;
                    
	# 3. DCL - GRANT,REVOKE,CREATE USER
    
			# 1. CREATE USER
					
                    CREATE USER 'VIJAY'@'LOCALHOST' IDENTIFIED BY '12345';
    
			# 2. GRANT
					
                    # 1. ALL PERMISSION TO ALL TABLES ON THAT DATABASE
						 GRANT ALL PRIVILEGES ON HR.* TO 'VIJAY'@'LOCALHOST';
                    
                    # 2. PARTICULAR PRIVILEGES TO ALL TABLES ON THAT DATABASE
						 GRANT SELECT ON MYSQL_TUTORIAL.* TO 'DUMMY'@'LOCALHOST';
                    
                    # 3. ALL PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 GRANT ALL PRIVILEGES ON HR.EMPLOYEES TO 'VIJAY'@'LOCALHOST';
                    
                    # 4. PARITICULAR PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 GRANT SELECT,INSERT ON HR.EMPLOYEES TO 'DUMMY'@'LOCALHOST';
			
            # 3. REVOKE
            
					# 1. REMOVE ALL PERMISSION TO ALL TABLES ON THAT DATABASE
						 REVOKE PRIVILEGES ON HR.* FROM 'VIJAY'@'LOCALHOST';
                    
                    # 2. REMOVE PARTICULAR PRIVILEGES TO ALL TABLES ON THAT DATABASE
						 REVOKE SELECT ON MYSQL_TUTORIAL.* FROM 'DUMMY'@'LOCALHOST';
                    
                    # 3. REMOVE ALL PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 REVOKE PRIVILEGES ON HR.EMPLOYEES FROM 'VIJAY'@'LOCALHOST';
                    
                    # 4. REMOVE PARITICULAR PERMISSION TO PARTICULAR TABLE ON THAT DATABASE
						 REVOKE SELECT,INSERT ON HR.EMPLOYEES FROM 'DUMMY'@'LOCALHOST';
                         
			
            # 4. DISPLAY ALL THE USER
            
					SELECT USER,HOST FROM MYSQL.USER;
                    
			# 5. DELETE THE USER
            
					DROP USER IF EXISTS 'DUMMY'@'LOCALHOST';
                    
			# 6. CHANGE THE USER PASSWORD
            
					ALTER USER 'VIJAY'@'LOCALHOST' IDENTIFIED BY '1234';
                    
			# 7. APPLY CHANGES
            
					FLUSH PRIVILEGES;
                    
	# 4. TCL - COMMIT, SAVEPOINT, ROLLBACK
					
					START TRANSACTION;
                    
                    UPDATE SIMPLE_TABLE
                    SET
						PHONE = '+91 1234567890'
					WHERE
						ID = 2;
                        
					SAVEPOINT QUARTERLY;
                    
                    UPDATE SIMPLE_TABLE
                    SET
						PHONE = '+91 2234567890'
					WHERE
						ID = 2;
                        
					SAVEPOINT HALFLY;
                    
                    ROLLBACK TO QUARTERLY;
                    COMMIT;
                    
	# 5. DQL - SELECT
    
			# 1. ALL FIELDS
					
                    SELECT * FROM SIMPLE_TABLE;
			
            # 2. PARTICULAR FIELDS ONLY
            
					SELECT ID,NAME FROM SIMPLE_TABLE;
                    
			# 3. USING WHERE CLAUSE
            
					SELECT ID,NAME FROM SIMPLE_TABLE
                    WHERE ID = 1;
                    
			# 4. ORDER PRINTING
            
					SELECT * FROM SIMPLE_TABLE ORDER BY NAME ASC;
                    SELECT * FROM SIMPLE_TABLE ORDER BY NAME DESC;
                    
			# 5. ONE OR MORE FILTER INSIDE WHERE
            
					SELECT * FROM SIMPLE_TABLE
                    WHERE
						ID = 1 AND NAME = 'VIJAY';
                        
# 6. AGGREGATION - SUM, COUNT, MIN, MAX, AVG

	# 1. SUM
			
            SELECT SUM(SALARY) AS TOTAL FROM EMPLOYEES;
            SELECT SUM(SALARY) AS TOTAL_DEPARTMENT_SALES FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;
            SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
            SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING TOTAL_SALARY > 100000;
            SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY TOTAL_SALARY DESC;
			SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY,
				CASE
					WHEN SUM(SALARY) > 100000 THEN 'HIGH SALARY'
					WHEN SUM(SALARY) BETWEEN 50000 AND 100000 THEN 'MEDIUM SALARY'
					ELSE 'LOW SALARY'
				END AS SALARY_CATEGORY
				FROM EMPLOYEES
				GROUP BY DEPARTMENT_ID
                ORDER BY TOTAL_SALARY;
            SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING TOTAL_SALARY > 36000 ORDER BY TOTAL_SALARY DESC LIMIT 1;
                
	# 2. COUNT
    
			SELECT COUNT(*) FROM EMPLOYEES;
            SELECT DISTINCT COUNT(*) FROM EMPLOYEES;
            SELECT COUNT(DEPARTMENT_ID) FROM EMPLOYEES;
            SELECT DISTINCT COUNT(DEPARTMENT_ID) FROM EMPLOYEES;
            SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY > 4000;
            SELECT DEPARTMENT_ID,COUNT(*) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
            SELECT DEPARTMENT_ID,COUNT(*) AS CNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING CNT > 10;
            SELECT DEPARTMENT_ID,COUNT(*) AS CNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY CNT;
            SELECT DEPARTMENT_ID,COUNT(*) AS CNT,
				CASE
					WHEN COUNT(*) > 10 THEN 'MORE CROWD'
                    WHEN COUNT(*) > 3 THEN 'AVERAGE CROWD'
                    ELSE 'BELOW CROWD'
				END AS 'CROWD COUNT'
                FROM EMPLOYEES
                GROUP BY DEPARTMENT_ID
                ORDER BY CNT ASC;
			SELECT DEPARTMENT_ID,COUNT(*) AS CNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING CNT > 5 ORDER BY CNT DESC LIMIT 2;
            
	# 3. AVG
    
			SELECT AVG(SALARY) FROM EMPLOYEES;
            SELECT AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
            SELECT DEPARTMENT_ID,AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
            SELECT DEPARTMENT_ID,AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG_SALARY > 7500;
            SELECT DEPARTMENT_ID,AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY AVG_SALARY DESC;
            SELECT DEPARTMENT_ID,AVG(SALARY) AS AVG_SALARY,
				CASE
					WHEN AVG(SALARY) > 7500 THEN 'BEST SALARY RANGE'
                    WHEN AVG(SALARY) BETWEEN 5000 AND 7500 THEN 'AVERAGE SALARY RANGE'
                    ELSE 'LOW SALARY RANGE'
				END AS 'SALARY RANGE'
                FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY AVG_SALARY;
			SELECT DEPARTMENT_ID,AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY AVG_SALARY DESC LIMIT 1;
            
	# 4. MAX
    
			SELECT MAX(SALARY) FROM EMPLOYEES;
            SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
			SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
            SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MAX(SALARY);
            SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 9000 ORDER BY MAX(SALARY);
            SELECT DEPARTMENT_ID,MAX(SALARY) AS MAX_SALARY,
				CASE
					WHEN MAX(SALARY) > 11000 THEN 'HIGH SALARY'
                    WHEN MAX(SALARY) BETWEEN 7000 AND 11000 THEN 'MIDDLE SALARY'
                    ELSE 'POOR SALARY'
				END AS CATEGORY_SALARY
                FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MAX(SALARY) DESC;
			SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MAX(SALARY) DESC LIMIT 1;
            
	# 5. MIN
    
			SELECT MIN(SALARY) FROM EMPLOYEES;
            SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
			SELECT DEPARTMENT_ID,MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
            SELECT DEPARTMENT_ID,MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MIN(SALARY);
            SELECT DEPARTMENT_ID,MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MIN(SALARY) > 9000 ORDER BY MIN(SALARY);
            SELECT DEPARTMENT_ID,MIN(SALARY) AS MIN_SALARY,
				CASE
					WHEN MIN(SALARY) > 11000 THEN 'HIGH SALARY'
                    WHEN MIN(SALARY) BETWEEN 7000 AND 11000 THEN 'MIDDLE SALARY'
                    ELSE 'POOR SALARY'
				END AS CATEGORY_SALARY
                FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MIN(SALARY) DESC;
			SELECT DEPARTMENT_ID,MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY MIN(SALARY) DESC LIMIT 1;
            
# 7. SUB QUERIES

	# 1. FIELD WISE
    
			SELECT DEPARTMENT_ID,(SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
		
	# 2. AT FROM
    
			SELECT FIRST_NAME,SALARY FROM (SELECT * FROM EMPLOYEES) AS SUB_QUERY;
            
	# 3. WHERE CLAUSE
    
			SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE SALARY > 15200);
            SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 122);
            SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE EXISTS (SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 100);
            
	# 4. CASE STATEMENT
    
			SELECT FIRST_NAME,SALARY,
				CASE
					WHEN SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE FIRST_NAME = 'DIANA') THEN 'ABOVE AVERAGE'
                    ELSE 'BELOW AVERAGE'
				END AS CATEGORY_SALARY
                FROM EMPLOYEES;
            
            
# 8. VIEWS

			CREATE VIEW SQL_VIEW AS (
				SELECT * FROM SIMPLE_TABLE
			);
            
            SELECT * FROM SQL_VIEW;
            
            INSERT INTO SIMPLE_TABLE (ID,NAME,ADDRESS,DOB,EMAIL,PHONE,AMOUNT)
			VALUES(3,'DUMMY','CHENNAI','2000-11-13 11:00:09','DUMMY@GMAIL.COM','+91 7839729834','900.00');
            
# 9. JOINS - INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN, CROSS JOIN, SELF JOIN

		# 1. INNER JOIN
        
			SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
            INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
            
            WITH DEPARTMENT_WISE AS (
				SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
				INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
			)
            SELECT DEPARTMENT_NAME,COUNT(*) CNT FROM DEPARTMENT_WISE GROUP BY DEPARTMENT_NAME ORDER BY CNT ASC;
            
		# 2. LEFT JOIN
        
			SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
            LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
            
            WITH DEPARTMENT_WISE AS (
				SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
				LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
			)
            SELECT DEPARTMENT_NAME,COUNT(*) CNT FROM DEPARTMENT_WISE GROUP BY DEPARTMENT_NAME ORDER BY CNT ASC;
            
		# 3. RIGHT JOIN
        
			SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
            RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
            
            WITH DEPARTMENT_WISE AS (
				SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
				RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
			)
            SELECT DEPARTMENT_NAME,COUNT(*) CNT FROM DEPARTMENT_WISE GROUP BY DEPARTMENT_NAME ORDER BY CNT ASC;
            
		# 4. CROSS JOIN
        
			SELECT T.TOPPINGS,S.SIZE,C.TYPE
			FROM TOPPINGS T CROSS JOIN SIZES S CROSS JOIN CRUST C;
            
		# 5. SELF JOIN
        
			SELECT F.EMPLOYEE_ID,F.MANAGER_ID,F.FIRST_NAME AS EMPLOYEE_NAME,S.FIRST_NAME AS MANAGER_NAME FROM EMPLOYEES F
            LEFT JOIN EMPLOYEES S ON F.MANAGER_ID = S.EMPLOYEE_ID;
            
# 10. UNION, UNION ALL, INTERSECT, EXCEPT

		# 1. UNION 
        
			SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
			UNION
			SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;
        
        # 2.UNION ALL
        
			SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
			UNION ALL
			SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;
        
        # 3. INTERSECT
        
			SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
			INTERSECT
			SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;
        
        # 4. EXCEPT
        
			SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES_UNION
			EXCEPT
			SELECT FIRST_NAME,LAST_NAME FROM CONTRACTORS_UNION;
            
# 11. DATE TIME FUNCTION

		# 1. EXTRACTION
        
			SELECT EVENT_DATE,YEAR(EVENT_DATE) AS YEAR,MONTH(EVENT_DATE) AS MONTH,DAY(EVENT_DATE) AS DAY FROM EVENTS_DATE_TIME;
            
		# 2. ADDING AND SUBTRACTING DAYS
        
			SELECT EVENT_DATE,(EVENT_DATE + INTERVAL 30 DAY) AS 30_DAY_AFTER,(EVENT_DATE - INTERVAL 30 DAY) AS 30_DAY_BEFORE FROM EVENTS_DATE_TIME;
            
		# 3. TRANSFORMING DATE
        
			SELECT NOW() AS CURRENT_DATE_TIME;
            SELECT DAY(NOW()) AS TODAY_DATE;
            SELECT DATE(NOW()) AS DATE;
            SELECT YEAR(NOW()) AS YEAR;
            SELECT MONTH(NOW()) AS MONTH;
            SELECT DATE_FORMAT(NOW(), '%Y') AS CURRENT_YEAR_4DIGIT, DATE_FORMAT(NOW(), '%y') AS CURRENT_YEAR_2DIGIT;
            SELECT DATE_FORMAT(NOW(), '%M') AS CURRENT_MONTH_FULLY,DATE_FORMAT(NOW(), '%b') AS CURRENT_MONTH_ABR,DATE_FORMAT(NOW(), '%m') AS CURRENT_MONTH_NO;
            SELECT DATE_FORMAT(NOW(), '%D') AS CURRENT_DATE_WITH_TH,DATE_FORMAT(NOW(), '%d') AS CURRENT_DATE_NO,DATE_FORMAT(NOW(), '%e') AS CURRENT_DATE_NO;
            SELECT DATE_FORMAT(NOW(), '%W') AS CURRENT_DAY_OF_WEEK,DATE_FORMAT(NOW(), '%w') AS CURRENT_DAY_OF_WEEK_NO;
            SELECT DATE_FORMAT(NOW(), '%D %M %Y, %W') AS TODAY_DATE;
            
		# 4. TRANSFORMING TIME
        
			SELECT NOW() AS CURRENT_DATE_TIME;
            SELECT TIME(NOW()) AS TODAY_TIME;
            SELECT TIME(NOW()) AS TODAY_TIME,HOUR(NOW()) AS CURRENT_TIME_IN_HOUR;
            SELECT TIME(NOW()) AS TODAY_TIME,MINUTE(NOW()) AS CURRENT_MINUTE;
            SELECT TIME(NOW()) AS TODAY_TIME,SECOND(NOW()) AS CURRENT_SECONDS;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%H') AS CURRENT_TIME_IN_HOUR_24HR_FORMAT;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%h') AS CURRENT_TIME_IN_HOUR_12HR_FORMAT;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%i') AS CURRENT_TIME_IN_MINUTES_FORMAT;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%S %s') AS CURRENT_TIME_IN_SECONDS_FORMAT;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%p') AS CURRENT_TIME_AM_PM_FORMAT;
            SELECT TIME(NOW()) AS TODAY_TIME,DATE_FORMAT(NOW(), '%h:%i:%s - %p') AS CURRENT_TIME_FORMAT;
            SELECT DATE_FORMAT(NOW(), '%W, %D %M %Y, %h:%i:%s - %p') AS CURRENT_DATE_TIME;
            
# 12. REGEX EXAMPLE

		SELECT * FROM REGEX_SAMPLES;
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^A';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Z]';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[^A-Z]';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[^0-9]';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'E$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '[A-Z]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '[^A-Z]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '[^0-9]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '[0-9]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Z].*[0-9]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9].*[0-9]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9].*[A-Z]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Z].*[A-Z]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[A-Z].?[A-Z]$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'A{1}';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'N{1,}';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP 'P{2}';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '1|F';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^.{1,3}$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^F.+$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^F.?$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^F.*$';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '(.)\\1';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]{3}';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^[0-9]{3,}[A-Z]{3}$';
        SELECT * FROM REGEX_DEMO;
        SELECT * FROM REGEX_DEMO WHERE DATE_COL REGEXP '^[0-9]{4}[0-9]{2}[0-9]{2}';
        SELECT * FROM REGEX_DEMO WHERE DATE_COL REGEXP '^[0-9]{4}[-][0-9]{2}[-][0-9]{2}';
        SELECT * FROM REGEX_DEMO WHERE NOTES REGEXP '^[A-Z0-9].* CA{1}';
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^\\d'; 
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '^\\D'; 
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '\\D$'; 
		SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '\\d$'; 
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '\\b[A-C]'; 
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '[F-R]\\b'; 
        SELECT * FROM REGEX_SAMPLES WHERE SAMPLE_TEXT REGEXP '\\bRUNNING\\b';
        
# 13. STRING FUNCTIONS

		SELECT * FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,LENGTH(CUSTOMER_NAME) AS LEN_OF_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,UPPER(CUSTOMER_NAME) AS NAME_IN_UPPERCASE FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,LOWER(CUSTOMER_NAME) AS NAME_IN_LOWERCASE FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,SUBSTR(CUSTOMER_NAME,1,5) AS NAME_IN_UPPERCASE FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,CITY,CONCAT(CUSTOMER_NAME,'_',CITY) AS CONCAT_NAME_CITY FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,LEFT(CUSTOMER_NAME,5) AS FIRST_5_LETTERS FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,RIGHT(CUSTOMER_NAME,5) AS LAST_5_LETTERS FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,INSTR(CUSTOMER_NAME,' ') AS POS_OF_SPACE FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,SUBSTR(CUSTOMER_NAME,1,INSTR(CUSTOMER_NAME,' ')) AS FIRST_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,SUBSTR(CUSTOMER_NAME,INSTR(CUSTOMER_NAME,' ')+1,LENGTH(CUSTOMER_NAME)) AS LAST_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,LTRIM(SUBSTR(CUSTOMER_NAME,INSTR(CUSTOMER_NAME,' '),LENGTH(CUSTOMER_NAME))) AS LAST_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,RTRIM(SUBSTR(CUSTOMER_NAME,1,INSTR(CUSTOMER_NAME,' '))) AS LAST_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,TRIM(CUSTOMER_NAME) AS REMOVE_SPACES FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,LPAD(CUSTOMER_NAME,15,'#') AS LEFT_PAD FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,RPAD(CUSTOMER_NAME,15,'#') AS RIGHT_PAD FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,REPLACE(CUSTOMER_NAME,' ','_') AS FULL_NAME FROM CUSTOMERS;
        SELECT CUSTOMER_NAME,REVERSE(CUSTOMER_NAME) AS REV_NAME FROM CUSTOMERS;
        
# 14. WINDOW FUNCTIONS - AGGREGATION,RANK,VALUE

		# 1. AGGREGATION - SUM, COUNT, MAX, MIN, AVG
        
			# 1. SUM

				SELECT *,
				SUM(SALES_AMOUNT) OVER() AS TOTAL_AMOUNT FROM SALES;

				SELECT *,
                SUM(SALES_AMOUNT) OVER(ORDER BY SALES_AMOUNT) AS TOTAL_AMOUNT_INCREASING FROM SALES;
                
                SELECT *,
                SUM(SALES_AMOUNT) OVER(PARTITION BY STORE) AS STORE_WISE_TOTAL FROM SALES;
                
                SELECT *,
                SUM(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS STORE_WISE_INCREASING FROM SALES;
                
			# 2. COUNT
            
				SELECT *,
                COUNT(STORE) OVER() AS TOTAL_STORE_COUNT FROM SALES;
                
                SELECT *,
                COUNT(STORE) OVER(PARTITION BY STORE ORDER BY STORE) AS TOTAL_STORE_COUNT FROM SALES;
                
			# 3. AVG
            
				SELECT *,
                AVG(SALES_AMOUNT) OVER() AS AVG_SALES FROM SALES;
                
                SELECT *,
                AVG(SALES_AMOUNT) OVER(ORDER BY SALES_AMOUNT) AS INCREASING_AVG FROM SALES;
                
                SELECT *,
                AVG(SALES_AMOUNT) OVER(PARTITION BY STORE) AS STORE_WISE_AVG FROM SALES;
                
                SELECT *,
                AVG(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS STORE_WISE_INCREASING_AVG FROM SALES;
                
			# 4. MAX
            
				SELECT *,
                MAX(SALES_AMOUNT) OVER() MAX_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MAX(SALES_AMOUNT) OVER(ORDER BY STORE) STORE_WISE_MAX_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MAX(SALES_AMOUNT) OVER(PARTITION BY STORE) STORE_WISE_MAX_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MAX(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY STORE) STORE_WISE_MAX_SALES_AMOUNT FROM SALES;
                
			# 5. MIN
            
				SELECT *,
                MIN(SALES_AMOUNT) OVER() MIN_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MIN(SALES_AMOUNT) OVER(ORDER BY STORE) AS STORE_WISE_MIN_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MIN(SALES_AMOUNT) OVER(PARTITION BY STORE) AS STORE_WISE_MIN_SALES_AMOUNT FROM SALES;
                
                SELECT *,
                MIN(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY STORE) AS STORE_WISE_MIN_SALES_AMOUNT FROM SALES;
                
		# 2. RANK
        
			# 1. ROW_NUMBER()
            
				SELECT *,
                ROW_NUMBER() OVER() FROM SALES;
                
                SELECT *,
                ROW_NUMBER() OVER(ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
                
                SELECT *,
                ROW_NUMBER() OVER(PARTITION BY STORE) AS STORE_WISE FROM SALES;
                
                SELECT *,
                ROW_NUMBER() OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS STORE_WITH_SALES_AMOUNT_WISE FROM SALES;
                
			# 2. RANK()
            
				SELECT *,
                RANK() OVER(ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
                
                SELECT *,
                RANK() OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
			
            # 3. DENSE_RANK()
            
				SELECT *,
                DENSE_RANK() OVER(ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
                
                SELECT *,
                DENSE_RANK() OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
                
			# 4. PERCENT_RANK()
            
				SELECT *,
                PERCENT_RANK() OVER(ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
                
                SELECT *,
                PERCENT_RANK() OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS SALES_AMOUNT_WISE FROM SALES;
			
            # 5. NTILE()
            
				SELECT *,
                NTILE(4) OVER() AS GROUP_AS_PER_NORMAL FROM SALES;
                
                SELECT *,
                NTILE(4) OVER(ORDER BY SALES_AMOUNT ASC) AS GROUP_SALES_AMOUNT_BASED FROM SALES;
                
		# 3. VALUE()
        
			# 1. LAG()
            
				SELECT *,
                LAG(SALES_AMOUNT) OVER() AS PREV_SALES_AMOUNT FROM SALES;
                
				SELECT *,
                LAG(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS STORE_WISE_PREV_SALES_AMOUNT FROM SALES;
                
			# 2. LEAD()
            
				SELECT *,
                LEAD(SALES_AMOUNT) OVER() AS NEXT_SALES_AMOUNT FROM SALES;
                
				SELECT *,
                LEAD(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS STORE_WISE_NEXT_SALES_AMOUNT FROM SALES;
			
            # 3. FIRST_VALUE()
            
				SELECT *,
                FIRST_VALUE(SALES_AMOUNT) OVER() AS OVERALL_1ST_VALUE FROM SALES;
                
                SELECT *,
                FIRST_VALUE(SALES_AMOUNT) OVER(PARTITION BY STORE) AS STORE_1ST_VALUE FROM SALES;
                
                
			# 4. LAST_VALUE()
            
				SELECT *,
                LAST_VALUE(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS STORE_WISE_LATEST_VALUE FROM SALES;
        
				SELECT *,
                LAST_VALUE(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LATEST_SALES_AMOUNT,
                LAST_VALUE(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)  - SALES_AMOUNT AS DIFF_SALES_AMOUNT FROM SALES;
                
			# 5. NTH_VALUE()
            
				SELECT *,
                NTH_VALUE(SALES_AMOUNT,2) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SECOND_SALES_AMOUNT_STORE_WISE FROM SALES;
                